(function() {

    "use strict";

    define(

        function() {
            var acsFieldsConfig = new function() {
            var self = this;
			self.fields = 
			[
			   {
			      "fieldName":"ACRES",
			      "fieldAlias":"ACRES",
			      "fieldType":"Number",
			      "tableHeader":"Acres",
			      "category":"General",
			      "rowID":1,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"SQMI",
			      "fieldAlias":"SQMI",
			      "fieldType":"Number",
			      "tableHeader":"Square Miles",
			      "category":"General",
			      "rowID":2,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_POP",
			      "fieldAlias":"TOTAL_POP",
			      "fieldType":"Number",
			      "tableHeader":"Total Population",
			      "category":"General",
			      "rowID":3,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MEDIAN_AGE",
			      "fieldAlias":"MEDIAN_AGE",
			      "fieldType":"Number",
			      "tableHeader":"Median Age",
			      "category":"Age",
			      "rowID":4,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"UNDER5",
			      "fieldAlias":"UNDER5",
			      "fieldType":"Number",
			      "tableHeader":"Under 5",
			      "category":"Age",
			      "rowID":5,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_UNDER5",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE5TO17",
			      "fieldAlias":"AGE5TO17",
			      "fieldType":"Number",
			      "tableHeader":"5 to 17",
			      "category":"Age",
			      "rowID":6,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_5TO17",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE18TO34",
			      "fieldAlias":"AGE18TO34",
			      "fieldType":"Number",
			      "tableHeader":"18 to 34",
			      "category":"Age",
			      "rowID":7,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_18TO34",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE35TO49",
			      "fieldAlias":"AGE35TO49",
			      "fieldType":"Number",
			      "tableHeader":"35 to 49",
			      "category":"Age",
			      "rowID":8,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_35TO49",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE50TO64",
			      "fieldAlias":"AGE50TO64",
			      "fieldType":"Number",
			      "tableHeader":"50 to 64",
			      "category":"Age",
			      "rowID":9,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_50TO64",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE65TO84",
			      "fieldAlias":"AGE65TO84",
			      "fieldType":"Number",
			      "tableHeader":"65 to 84",
			      "category":"Age",
			      "rowID":10,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_65TO84",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE85PLUS",
			      "fieldAlias":"AGE85PLUS",
			      "fieldType":"Number",
			      "tableHeader":"85 and over",
			      "category":"Age",
			      "rowID":11,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_85PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE50PLUS",
			      "fieldAlias":"AGE50PLUS",
			      "fieldType":"Number",
			      "tableHeader":"50 and over",
			      "category":"Age",
			      "rowID":12,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_50PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE60PLUS",
			      "fieldAlias":"AGE60PLUS",
			      "fieldType":"Number",
			      "tableHeader":"60 and over",
			      "category":"Age",
			      "rowID":13,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_60PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE65PLUS",
			      "fieldAlias":"AGE65PLUS",
			      "fieldType":"Number",
			      "tableHeader":"65 and over",
			      "category":"Age",
			      "rowID":14,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_65PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE70PLUS",
			      "fieldAlias":"AGE70PLUS",
			      "fieldType":"Number",
			      "tableHeader":"70 and over",
			      "category":"Age",
			      "rowID":15,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_70PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE75PLUS",
			      "fieldAlias":"AGE75PLUS",
			      "fieldType":"Number",
			      "tableHeader":"75 and over",
			      "category":"Age",
			      "rowID":16,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_AGE_75PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AGE25PLUS",
			      "fieldAlias":"AGE25PLUS",
			      "fieldType":"Number",
			      "tableHeader":"25 and over",
			      "category":"Age",
			      "rowID":17,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"Age",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_MALE",
			      "fieldAlias":"TOTAL_MALE",
			      "fieldType":"Number",
			      "tableHeader":"Male Population",
			      "category":"Age By Gender",
			      "rowID":18,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y5LESS5",
			      "fieldAlias":"M_Y5LESS5",
			      "fieldType":"Number",
			      "tableHeader":"Males less than 5",
			      "category":"Age By Gender",
			      "rowID":19,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y5TO9",
			      "fieldAlias":"M_Y5TO9",
			      "fieldType":"Number",
			      "tableHeader":"Males age 5 to 9",
			      "category":"Age By Gender",
			      "rowID":20,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y10TO14",
			      "fieldAlias":"M_Y10TO14",
			      "fieldType":"Number",
			      "tableHeader":"Males age 10 to 14",
			      "category":"Age By Gender",
			      "rowID":21,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y15TO17",
			      "fieldAlias":"M_Y15TO17",
			      "fieldType":"Number",
			      "tableHeader":"Males age 15 to 17",
			      "category":"Age By Gender",
			      "rowID":22,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y18TO19",
			      "fieldAlias":"M_Y18TO19",
			      "fieldType":"Number",
			      "tableHeader":"Males age 18 to 19",
			      "category":"Age By Gender",
			      "rowID":23,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y20",
			      "fieldAlias":"M_Y20",
			      "fieldType":"Number",
			      "tableHeader":"Males age 20",
			      "category":"Age By Gender",
			      "rowID":24,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y21",
			      "fieldAlias":"M_Y21",
			      "fieldType":"Number",
			      "tableHeader":"Males age 21",
			      "category":"Age By Gender",
			      "rowID":25,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y22TO24",
			      "fieldAlias":"M_Y22TO24",
			      "fieldType":"Number",
			      "tableHeader":"Males age 22 to 24",
			      "category":"Age By Gender",
			      "rowID":26,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y25TO29",
			      "fieldAlias":"M_Y25TO29",
			      "fieldType":"Number",
			      "tableHeader":"Males age 25 to 29",
			      "category":"Age By Gender",
			      "rowID":27,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y30TO34",
			      "fieldAlias":"M_Y30TO34",
			      "fieldType":"Number",
			      "tableHeader":"Males age 30 to 34",
			      "category":"Age By Gender",
			      "rowID":28,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y35TO39",
			      "fieldAlias":"M_Y35TO39",
			      "fieldType":"Number",
			      "tableHeader":"Males age 35 to 39",
			      "category":"Age By Gender",
			      "rowID":29,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y40TO44",
			      "fieldAlias":"M_Y40TO44",
			      "fieldType":"Number",
			      "tableHeader":"Males age 40 to 44",
			      "category":"Age By Gender",
			      "rowID":30,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y45TO49",
			      "fieldAlias":"M_Y45TO49",
			      "fieldType":"Number",
			      "tableHeader":"Males age 45 to 49",
			      "category":"Age By Gender",
			      "rowID":31,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y50TO54",
			      "fieldAlias":"M_Y50TO54",
			      "fieldType":"Number",
			      "tableHeader":"Males age 50 to 54",
			      "category":"Age By Gender",
			      "rowID":32,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y55TO59",
			      "fieldAlias":"M_Y55TO59",
			      "fieldType":"Number",
			      "tableHeader":"Males age 55 to 59",
			      "category":"Age By Gender",
			      "rowID":33,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y60TO61",
			      "fieldAlias":"M_Y60TO61",
			      "fieldType":"Number",
			      "tableHeader":"Males age 60 to 61",
			      "category":"Age By Gender",
			      "rowID":34,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y62TO64",
			      "fieldAlias":"M_Y62TO64",
			      "fieldType":"Number",
			      "tableHeader":"Males age 62 to 64",
			      "category":"Age By Gender",
			      "rowID":35,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y65TO66",
			      "fieldAlias":"M_Y65TO66",
			      "fieldType":"Number",
			      "tableHeader":"Males age 65 to 66",
			      "category":"Age By Gender",
			      "rowID":36,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y67TO69",
			      "fieldAlias":"M_Y67TO69",
			      "fieldType":"Number",
			      "tableHeader":"Males age 67 to 69",
			      "category":"Age By Gender",
			      "rowID":37,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y70TO74",
			      "fieldAlias":"M_Y70TO74",
			      "fieldType":"Number",
			      "tableHeader":"Males age 70 to 74",
			      "category":"Age By Gender",
			      "rowID":38,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y75TO79",
			      "fieldAlias":"M_Y75TO79",
			      "fieldType":"Number",
			      "tableHeader":"Males age 75 to 79",
			      "category":"Age By Gender",
			      "rowID":39,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y80TO84",
			      "fieldAlias":"M_Y80TO84",
			      "fieldType":"Number",
			      "tableHeader":"Males age 80 to 84",
			      "category":"Age By Gender",
			      "rowID":40,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"M_Y85UP",
			      "fieldAlias":"M_Y85UP",
			      "fieldType":"Number",
			      "tableHeader":"Males age 85 or older",
			      "category":"Age By Gender",
			      "rowID":41,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_FEMALE",
			      "fieldAlias":"TOTAL_FEMALE",
			      "fieldType":"Number",
			      "tableHeader":"Female Population",
			      "category":"Age By Gender",
			      "rowID":42,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y5LESS5",
			      "fieldAlias":"F_Y5LESS5",
			      "fieldType":"Number",
			      "tableHeader":"Females less than 5",
			      "category":"Age By Gender",
			      "rowID":43,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y5TO9",
			      "fieldAlias":"F_Y5TO9",
			      "fieldType":"Number",
			      "tableHeader":"Females age 5 to 9",
			      "category":"Age By Gender",
			      "rowID":44,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y10TO14",
			      "fieldAlias":"F_Y10TO14",
			      "fieldType":"Number",
			      "tableHeader":"Females age 10 to 14",
			      "category":"Age By Gender",
			      "rowID":45,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y15TO17",
			      "fieldAlias":"F_Y15TO17",
			      "fieldType":"Number",
			      "tableHeader":"Females age 15 to 17",
			      "category":"Age By Gender",
			      "rowID":46,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y18TO19",
			      "fieldAlias":"F_Y18TO19",
			      "fieldType":"Number",
			      "tableHeader":"Females age 18 to 19",
			      "category":"Age By Gender",
			      "rowID":47,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y20",
			      "fieldAlias":"F_Y20",
			      "fieldType":"Number",
			      "tableHeader":"Females age 20",
			      "category":"Age By Gender",
			      "rowID":48,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y21",
			      "fieldAlias":"F_Y21",
			      "fieldType":"Number",
			      "tableHeader":"Females age 21",
			      "category":"Age By Gender",
			      "rowID":49,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y22TO24",
			      "fieldAlias":"F_Y22TO24",
			      "fieldType":"Number",
			      "tableHeader":"Females age 22 to 24",
			      "category":"Age By Gender",
			      "rowID":50,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y25TO29",
			      "fieldAlias":"F_Y25TO29",
			      "fieldType":"Number",
			      "tableHeader":"Females age 25 to 29",
			      "category":"Age By Gender",
			      "rowID":51,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y30TO34",
			      "fieldAlias":"F_Y30TO34",
			      "fieldType":"Number",
			      "tableHeader":"Females age 30 to 34",
			      "category":"Age By Gender",
			      "rowID":52,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y35TO39",
			      "fieldAlias":"F_Y35TO39",
			      "fieldType":"Number",
			      "tableHeader":"Females age 35 to 39",
			      "category":"Age By Gender",
			      "rowID":53,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y40TO44",
			      "fieldAlias":"F_Y40TO44",
			      "fieldType":"Number",
			      "tableHeader":"Females age 40 to 44",
			      "category":"Age By Gender",
			      "rowID":54,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y45TO49",
			      "fieldAlias":"F_Y45TO49",
			      "fieldType":"Number",
			      "tableHeader":"Females age 45 to 49",
			      "category":"Age By Gender",
			      "rowID":55,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y50TO54",
			      "fieldAlias":"F_Y50TO54",
			      "fieldType":"Number",
			      "tableHeader":"Females age 50 to 54",
			      "category":"Age By Gender",
			      "rowID":56,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y55TO59",
			      "fieldAlias":"F_Y55TO59",
			      "fieldType":"Number",
			      "tableHeader":"Females age 55 to 59",
			      "category":"Age By Gender",
			      "rowID":57,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y60TO61",
			      "fieldAlias":"F_Y60TO61",
			      "fieldType":"Number",
			      "tableHeader":"Females age 60 to 61",
			      "category":"Age By Gender",
			      "rowID":58,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y62TO64",
			      "fieldAlias":"F_Y62TO64",
			      "fieldType":"Number",
			      "tableHeader":"Females age 62 to 64",
			      "category":"Age By Gender",
			      "rowID":59,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y65TO66",
			      "fieldAlias":"F_Y65TO66",
			      "fieldType":"Number",
			      "tableHeader":"Females age 65 to 66",
			      "category":"Age By Gender",
			      "rowID":60,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y67TO69",
			      "fieldAlias":"F_Y67TO69",
			      "fieldType":"Number",
			      "tableHeader":"Females age 67 to 69",
			      "category":"Age By Gender",
			      "rowID":61,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y70TO74",
			      "fieldAlias":"F_Y70TO74",
			      "fieldType":"Number",
			      "tableHeader":"Females age 70 to 74",
			      "category":"Age By Gender",
			      "rowID":62,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y75TO79",
			      "fieldAlias":"F_Y75TO79",
			      "fieldType":"Number",
			      "tableHeader":"Females age 75 to 79",
			      "category":"Age By Gender",
			      "rowID":63,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y80TO84",
			      "fieldAlias":"F_Y80TO84",
			      "fieldType":"Number",
			      "tableHeader":"Females age 80 to 84",
			      "category":"Age By Gender",
			      "rowID":64,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"F_Y85UP",
			      "fieldAlias":"F_Y85UP",
			      "fieldType":"Number",
			      "tableHeader":"Females age 85 or older",
			      "category":"Age By Gender",
			      "rowID":65,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"WHITE",
			      "fieldAlias":"WHITE",
			      "fieldType":"Number",
			      "tableHeader":"White",
			      "category":"Race",
			      "rowID":66,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"ACS 2014",
			      "percentField":"PCT_WHITE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"BLACK",
			      "fieldAlias":"BLACK",
			      "fieldType":"Number",
			      "tableHeader":"Black",
			      "category":"Race",
			      "rowID":67,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_BLACK",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NATIVE",
			      "fieldAlias":"NATIVE",
			      "fieldType":"Number",
			      "tableHeader":"Native American",
			      "category":"Race",
			      "rowID":68,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_NATIVE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ASIAN",
			      "fieldAlias":"ASIAN",
			      "fieldType":"Number",
			      "tableHeader":"Asian",
			      "category":"Race",
			      "rowID":69,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ASIAN",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"PACIFIC",
			      "fieldAlias":"PACIFIC",
			      "fieldType":"Number",
			      "tableHeader":"Pacific Islander",
			      "category":"Race",
			      "rowID":70,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_PACIFIC",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"OTHER",
			      "fieldAlias":"OTHER",
			      "fieldType":"Number",
			      "tableHeader":"Other",
			      "category":"Race",
			      "rowID":71,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_OTHER",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TWO_OR_MORE",
			      "fieldAlias":"TWO_OR_MORE",
			      "fieldType":"Number",
			      "tableHeader":"Two or More",
			      "category":"Race",
			      "rowID":72,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_TWO_OR_MORE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HISPANIC",
			      "fieldAlias":"HISPANIC",
			      "fieldType":"Number",
			      "tableHeader":"Hispanic",
			      "category":"Ethnicity",
			      "rowID":73,
			      "groupID":"<span class='myHiddenClass'>05</span>Population by Ethnicity",
			      "chartCategory":"Ethnicity",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HISPANIC",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NOT_HISPANIC",
			      "fieldAlias":"Non-Hispanic",
			      "fieldType":"Number",
			      "tableHeader":"Non-Hispanic",
			      "category":"Ethnicity",
			      "rowID":74,
			      "groupID":"<span class='myHiddenClass'>05</span>Population by Ethnicity",
			      "chartCategory":"Ethnicity",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_NOT_HISPANIC",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MINORITY_POP",
			      "fieldAlias":"MINORITY_POP",
			      "fieldType":"Number",
			      "tableHeader":"Minority Population",
			      "category":"General",
			      "rowID":75,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_MINORITY",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_FAMILIES",
			      "fieldAlias":"TOTAL_FAMILIES",
			      "fieldType":"Number",
			      "tableHeader":"Total Families",
			      "category":"General",
			      "rowID":76,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_HOUSEHOLDS",
			      "fieldAlias":"TOTAL_HOUSEHOLDS",
			      "fieldType":"Number",
			      "tableHeader":"Total Households",
			      "category":"Housholds",
			      "rowID":77,
			      "groupID":"<span class='myHiddenClass'>06</span>Households",
			      "chartCategory":"Housholds",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AVG_HH_SIZE",
			      "fieldAlias":"AVG_HH_SIZE",
			      "fieldType":"Number",
			      "tableHeader":"Average Household Size",
			      "category":"Housholds",
			      "rowID":78,
			      "groupID":"<span class='myHiddenClass'>06</span>Households",
			      "chartCategory":"Housholds",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"LINGLSO_HH",
			      "fieldAlias":"LINGLSO_HH",
			      "fieldType":"Number",
			      "tableHeader":"Linguistically Isolated Households",
			      "category":"Housholds",
			      "rowID":79,
			      "groupID":"<span class='myHiddenClass'>06</span>Households",
			      "chartCategory":"Housholds",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_LINGISO_HH",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MEDIAN_HOUSEHOLD_INCOME",
			      "fieldAlias":"MEDIAN_HOUSEHOLD_INCOME",
			      "fieldType":"Number",
			      "tableHeader":"Median Household Income",
			      "category":"Houshold Income",
			      "rowID":80,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"PER_CAPITA_INCOME",
			      "fieldAlias":"PER_CAPITA_INCOME",
			      "fieldType":"Number",
			      "tableHeader":"Per Capita Income",
			      "category":"Houshold Income",
			      "rowID":81,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"INCOME_BELOW_POVERTY_LEVEL",
			      "fieldAlias":"INCOME_BELOW_POVERTY_LEVEL",
			      "fieldType":"Number",
			      "tableHeader":"Income Below Poverty Level",
			      "category":"Houshold Income",
			      "rowID":82,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_POVERTY",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"INCOME_NOT_BELOW_POVERTY_LEVEL",
			      "fieldAlias":"INCOME_NOT_BELOW_POVERTY_LEVEL",
			      "fieldType":"Number",
			      "tableHeader":"Income Not Below Poverty Level",
			      "category":"Houshold Income",
			      "rowID":83,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_NOT_POVERTY",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HH_LESS_THAN_25K",
			      "fieldAlias":"HH_LESS_THAN_25K",
			      "fieldType":"Number",
			      "tableHeader":"Household Income Less Than 25K",
			      "category":"Houshold Income",
			      "rowID":84,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HH_LESS_THAN_25K",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HH_25K_TO_49K",
			      "fieldAlias":"HH_25K_TO_49K",
			      "fieldType":"Number",
			      "tableHeader":"Household Income 25K To 49K",
			      "category":"Houshold Income",
			      "rowID":85,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HH_25K_TO_49K",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HH_50K_TO_99K",
			      "fieldAlias":"HH_50K_TO_99K",
			      "fieldType":"Number",
			      "tableHeader":"Household Income 50K To 99K",
			      "category":"Houshold Income",
			      "rowID":86,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HH_50K_TO_99K",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HH_100K_PLUS",
			      "fieldAlias":"HH_100K_PLUS",
			      "fieldType":"Number",
			      "tableHeader":"Household Income 100K Plus",
			      "category":"Houshold Income",
			      "rowID":87,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HH_100K_PLUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_HU",
			      "fieldAlias":"TOTAL_HU",
			      "fieldType":"Number",
			      "tableHeader":"Total Housing Units",
			      "category":"Housing Units",
			      "rowID":88,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_OCCUPIED_HU",
			      "fieldAlias":"TOTAL_OCCUPIED_HU",
			      "fieldType":"Number",
			      "tableHeader":"Total Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":89,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"OCCUPIED_HU",
			      "fieldAlias":"OCCUPIED_HU",
			      "fieldType":"Number",
			      "tableHeader":"Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":90,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_OWNER_OCCUPIED_HU",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"VACANT_HU",
			      "fieldAlias":"VACANT_HU",
			      "fieldType":"Number",
			      "tableHeader":"Vacant Housing Units",
			      "category":"Housing Units",
			      "rowID":91,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_RENTER_OCCUPIED_HU",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"SEASONAL_HU",
			      "fieldAlias":"SEASONAL_HU",
			      "fieldType":"Number",
			      "tableHeader":"Seasonal Housing Units",
			      "category":"Housing Units",
			      "rowID":92,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_SEASONAL_HU",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NON_SEASONAL_HU",
			      "fieldAlias":"NON_SEASONAL_HU",
			      "fieldType":"Number",
			      "tableHeader":"Non Seasonal Housing Units",
			      "category":"Housing Units",
			      "rowID":93,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NON_SEASONAL_VAC_HU",
			      "fieldAlias":"NON_SEASONAL_VAC_HU",
			      "fieldType":"Number",
			      "tableHeader":"Non Seasonal Vac Housing Units",
			      "category":"Housing Units",
			      "rowID":94,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"OWNER_OCC_HU",
			      "fieldAlias":"OWNER_OCC_HU",
			      "fieldType":"Number",
			      "tableHeader":"Owner Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":95,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"RENTER_OCC_HU",
			      "fieldAlias":"RENTER_OCC_HU",
			      "fieldType":"Number",
			      "tableHeader":"Renter Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":96,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AVG_HH_SIZE_OWNER_HU",
			      "fieldAlias":"AVG_HH_SIZE_OWNER_HU",
			      "fieldType":"Number",
			      "tableHeader":"Avgerage Household Size Owner Housing Units",
			      "category":"Housing Units",
			      "rowID":97,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"AVG_HH_SIZE_RENTER_HU",
			      "fieldAlias":"AVG_HH_SIZE_RENTER_HU",
			      "fieldType":"Number",
			      "tableHeader":"Average Houshold Size Renter Housing Units",
			      "category":"Housing Units",
			      "rowID":98,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"VACANCY_RATE",
			      "fieldAlias":"VACANCY_RATE",
			      "fieldType":"Number",
			      "tableHeader":"Vacancy Rate",
			      "category":"Housing Units",
			      "rowID":99,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"SEASONAL_VACANCY_RATE",
			      "fieldAlias":"SEASONAL_VACANCY_RATE",
			      "fieldType":"Number",
			      "tableHeader":"Seasonal Vacancy Rate",
			      "category":"Housing Units",
			      "rowID":100,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NON_SEASONAL_VACANCY_RATE",
			      "fieldAlias":"NON_SEASONAL_VACANCY_RATE",
			      "fieldType":"Number",
			      "tableHeader":"Non Seasonal Vacancy Rate",
			      "category":"Housing Units",
			      "rowID":101,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MEDIAN_VALUE",
			      "fieldAlias":"MEDIAN_VALUE",
			      "fieldType":"Number",
			      "tableHeader":"Median Value",
			      "category":"Housing Units",
			      "rowID":102,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MEDIAN_GROSS_RENT",
			      "fieldAlias":"MEDIAN_GROSS_RENT",
			      "fieldType":"Number",
			      "tableHeader":"Median Gross Rent",
			      "category":"Housing Units",
			      "rowID":103,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Housing Units",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"LT9GRADE",
			      "fieldAlias":"LT9GRADE",
			      "fieldType":"Number",
			      "tableHeader":"Less than 9th Grade",
			      "category":"Education",
			      "rowID":104,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_LT9GRADE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NOHSDIPLOMA",
			      "fieldAlias":"NOHSDIPLOMA",
			      "fieldType":"Number",
			      "tableHeader":"No High School Diploma",
			      "category":"Education",
			      "rowID":105,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_NOHSDIPLOMA",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HSGRAD",
			      "fieldAlias":"HSGRAD",
			      "fieldType":"Number",
			      "tableHeader":"High School Graduate",
			      "category":"Education",
			      "rowID":106,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HSGRAD",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"SOMECOLLEGE",
			      "fieldAlias":"SOMECOLLEGE",
			      "fieldType":"Number",
			      "tableHeader":"Some college",
			      "category":"Education",
			      "rowID":107,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_SOMECOLLEGE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ASSOCIATES",
			      "fieldAlias":"ASSOCIATES",
			      "fieldType":"Number",
			      "tableHeader":"Associates",
			      "category":"Education",
			      "rowID":108,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ASSOCIATES",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"BACHELORS",
			      "fieldAlias":"BACHELORS",
			      "fieldType":"Number",
			      "tableHeader":"Bachelors",
			      "category":"Education",
			      "rowID":109,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_BACHELORS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"GRADPROF",
			      "fieldAlias":"GRADPROF",
			      "fieldType":"Number",
			      "tableHeader":"Graduate / Professional",
			      "category":"Education",
			      "rowID":110,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_GRADPROF",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TOTAL_WORKERS_16PLUS",
			      "fieldAlias":"TOTAL_WORKERS_16PLUS",
			      "fieldType":"Number",
			      "tableHeader":"Total Workers 16 Plus",
			      "category":"Modes of Transportation",
			      "rowID":111,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CIVPOP16PLUS",
			      "fieldAlias":"CIVPOP16PLUS",
			      "fieldType":"Number",
			      "tableHeader":"Civilian Population 16 Plus",
			      "category":"General",
			      "rowID":112,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CIVPOP18PLUS",
			      "fieldAlias":"CIVPOP18PLUS",
			      "fieldType":"Number",
			      "tableHeader":"Civilian Population 18 Plus",
			      "category":"General",
			      "rowID":113,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"VETERAN",
			      "fieldAlias":"VETERAN",
			      "fieldType":"Number",
			      "tableHeader":"Veteran",
			      "category":"General",
			      "rowID":114,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"General",
			      "chartType":"",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_VETERAN",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CAR_TRUCK_VAN",
			      "fieldAlias":"CAR_TRUCK_VAN",
			      "fieldType":"Number",
			      "tableHeader":"Car Truck Van",
			      "category":"Modes of Transportation",
			      "rowID":115,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_CAR_TRUCK_VAN",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"DROVE_ALONE",
			      "fieldAlias":"DROVE_ALONE",
			      "fieldType":"Number",
			      "tableHeader":"Drove Alone",
			      "category":"Modes of Transportation",
			      "rowID":116,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_DROVE_ALONE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CARPOOLED",
			      "fieldAlias":"CARPOOLED",
			      "fieldType":"Number",
			      "tableHeader":"Carpooled",
			      "category":"Modes of Transportation",
			      "rowID":117,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_CARPOOLED",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"BUS",
			      "fieldAlias":"BUS",
			      "fieldType":"Number",
			      "tableHeader":"Bus",
			      "category":"Modes of Transportation",
			      "rowID":118,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_BUS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"RAIL",
			      "fieldAlias":"RAIL",
			      "fieldType":"Number",
			      "tableHeader":"Rail",
			      "category":"Modes of Transportation",
			      "rowID":119,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_RAIL",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TAXI",
			      "fieldAlias":"TAXI",
			      "fieldType":"Number",
			      "tableHeader":"Taxi",
			      "category":"Modes of Transportation",
			      "rowID":120,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_TAXI",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MOTORCYCLE",
			      "fieldAlias":"MOTORCYCLE",
			      "fieldType":"Number",
			      "tableHeader":"Motorcycle",
			      "category":"Modes of Transportation",
			      "rowID":121,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_MOTORCYCLE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"BICYCLE",
			      "fieldAlias":"BICYCLE",
			      "fieldType":"Number",
			      "tableHeader":"Bicycle",
			      "category":"Modes of Transportation",
			      "rowID":122,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_BICYCLE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"WALKED",
			      "fieldAlias":"WALKED",
			      "fieldType":"Number",
			      "tableHeader":"Walked",
			      "category":"Modes of Transportation",
			      "rowID":123,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_WALKED",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"OTHER_MEANS",
			      "fieldAlias":"OTHER_MEANS",
			      "fieldType":"Number",
			      "tableHeader":"Other Means",
			      "category":"Modes of Transportation",
			      "rowID":124,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_OTHER_MEANS",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"WORKED_FROM_HOME",
			      "fieldAlias":"WORKED_FROM_HOME",
			      "fieldType":"Number",
			      "tableHeader":"Worked From Home",
			      "category":"Modes of Transportation",
			      "rowID":125,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_WORKED_FROM_HOME",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NO_VEHICLE",
			      "fieldAlias":"NO_VEHICLE",
			      "fieldType":"Number",
			      "tableHeader":"No Vehicle",
			      "category":"Modes of Transportation",
			      "rowID":126,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_NO_VEHICLE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ONE_VEHICLE",
			      "fieldAlias":"ONE_VEHICLE",
			      "fieldType":"Number",
			      "tableHeader":"One Vehicle",
			      "category":"Modes of Transportation",
			      "rowID":127,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ONE_VEHICLE",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"TWO_VEHICLES",
			      "fieldAlias":"TWO_VEHICLES",
			      "fieldType":"Number",
			      "tableHeader":"Two Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":128,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_TWO_VEHICLES",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"THREE_VEHICLES",
			      "fieldAlias":"THREE_VEHICLES",
			      "fieldType":"Number",
			      "tableHeader":"Three Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":129,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_THREE_VEHICLES",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"FOUR_VEHICLES",
			      "fieldAlias":"FOUR_VEHICLES",
			      "fieldType":"Number",
			      "tableHeader":"Four Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":130,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_FOUR_VEHICLES",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"FIVE_PLUS_VEHICLES",
			      "fieldAlias":"FIVE_PLUS_VEHICLES",
			      "fieldType":"Number",
			      "tableHeader":"Five Plus Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":131,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_FIVE_PLUS_VEHICLES",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MgBizSciArt",
			      "fieldAlias":"MgBizSciArt",
			      "fieldType":"Number",
			      "tableHeader":"Management, business, science, and arts occupations",
			      "category":"Occupation",
			      "rowID":132,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_MgBizSciArt",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MgBizFin",
			      "fieldAlias":"MgBizFin",
			      "fieldType":"Number",
			      "tableHeader":"Management, business, and financial occupations",
			      "category":"Occupation",
			      "rowID":133,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_MgBizFin",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"Mgmt",
			      "fieldAlias":"Mgmt",
			      "fieldType":"Number",
			      "tableHeader":"Management occupations",
			      "category":"Occupation",
			      "rowID":134,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_Mgmt",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"BizFin",
			      "fieldAlias":"BizFin",
			      "fieldType":"Number",
			      "tableHeader":"Business and financial operations occupations",
			      "category":"Occupation",
			      "rowID":135,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_BizFin",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CompEngSci",
			      "fieldAlias":"CompEngSci",
			      "fieldType":"Number",
			      "tableHeader":"Computer, engineering, and science occupations",
			      "category":"Occupation",
			      "rowID":136,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_CompEngSci",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CompMath",
			      "fieldAlias":"CompMath",
			      "fieldType":"Number",
			      "tableHeader":"Computer and mathematical occupations",
			      "category":"Occupation",
			      "rowID":137,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_CompMath",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ArchEngin",
			      "fieldAlias":"ArchEngin",
			      "fieldType":"Number",
			      "tableHeader":"Architecture and engineering occupations",
			      "category":"Occupation",
			      "rowID":138,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ArchEngin",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"LifePhysSocSci",
			      "fieldAlias":"LifePhysSocSci",
			      "fieldType":"Number",
			      "tableHeader":"Life, physical, and social science occupations",
			      "category":"Occupation",
			      "rowID":139,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_LifePhysSocSci",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"EduLegComArtMedia",
			      "fieldAlias":"EduLegComArtMedia",
			      "fieldType":"Number",
			      "tableHeader":"Education, legal, community service, arts, and media occupations",
			      "category":"Occupation",
			      "rowID":140,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_EduLegComArtMedia",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"CommSocServ",
			      "fieldAlias":"CommSocServ",
			      "fieldType":"Number",
			      "tableHeader":"Community and social service occupations",
			      "category":"Occupation",
			      "rowID":141,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_CommSocServ",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"Legal",
			      "fieldAlias":"Legal",
			      "fieldType":"Number",
			      "tableHeader":"Legal occupations",
			      "category":"Occupation",
			      "rowID":142,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_Legal",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"EduTrainLib",
			      "fieldAlias":"EduTrainLib",
			      "fieldType":"Number",
			      "tableHeader":"Education, training, and library occupations",
			      "category":"Occupation",
			      "rowID":143,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_EduTrainLib",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ArtEntSportMedia",
			      "fieldAlias":"ArtEntSportMedia",
			      "fieldType":"Number",
			      "tableHeader":"Arts, design, entertainment, sports, and media occupations",
			      "category":"Occupation",
			      "rowID":144,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ArtEntSportMedia",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HealthTechnical",
			      "fieldAlias":"HealthTechnical",
			      "fieldType":"Number",
			      "tableHeader":"Healthcare practitioners and technical occupations",
			      "category":"Occupation",
			      "rowID":145,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HealthTechnical",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HealthDiagTechOcc",
			      "fieldAlias":"HealthDiagTechOcc",
			      "fieldType":"Number",
			      "tableHeader":"Health diagnosing and treating practitioners and other technical occupations",
			      "category":"Occupation",
			      "rowID":146,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HealthDiagTechOcc",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HealthTech",
			      "fieldAlias":"HealthTech",
			      "fieldType":"Number",
			      "tableHeader":"Health technologists and technicians ",
			      "category":"Occupation",
			      "rowID":147,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HealthTech",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ServiceOcc",
			      "fieldAlias":"ServiceOcc",
			      "fieldType":"Number",
			      "tableHeader":"Service occupations",
			      "category":"Occupation",
			      "rowID":148,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ServiceOcc",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"HealthSupport",
			      "fieldAlias":"HealthSupport",
			      "fieldType":"Number",
			      "tableHeader":"Healthcare support occupations",
			      "category":"Occupation",
			      "rowID":149,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_HealthSupport",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ProtectiveServ",
			      "fieldAlias":"ProtectiveServ",
			      "fieldType":"Number",
			      "tableHeader":"Protective service occupations",
			      "category":"Occupation",
			      "rowID":150,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ProtectiveServ",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"Firefighting",
			      "fieldAlias":"Firefighting",
			      "fieldType":"Number",
			      "tableHeader":"Firefighting and prevention, and other protective service workers including supervisors",
			      "category":"Occupation",
			      "rowID":151,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_Firefighting",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"LawEnforcement",
			      "fieldAlias":"LawEnforcement",
			      "fieldType":"Number",
			      "tableHeader":"Law enforcement workers including supervisors",
			      "category":"Occupation",
			      "rowID":152,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_LawEnforcement",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"FoodPrep",
			      "fieldAlias":"FoodPrep",
			      "fieldType":"Number",
			      "tableHeader":"Food preparation and serving related occupations",
			      "category":"Occupation",
			      "rowID":153,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_FoodPrep",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"GroundsMaint",
			      "fieldAlias":"GroundsMaint",
			      "fieldType":"Number",
			      "tableHeader":"Building and grounds cleaning and maintenance occupations",
			      "category":"Occupation",
			      "rowID":154,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_GroundsMaint",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"PersonalCare",
			      "fieldAlias":"PersonalCare",
			      "fieldType":"Number",
			      "tableHeader":"Personal care and service occupations",
			      "category":"Occupation",
			      "rowID":155,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_PersonalCare",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"SalesOfficeOcc",
			      "fieldAlias":"SalesOfficeOcc",
			      "fieldType":"Number",
			      "tableHeader":"Sales and office occupations",
			      "category":"Occupation",
			      "rowID":156,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_SalesOfficeOcc",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"SalesOcc",
			      "fieldAlias":"SalesOcc",
			      "fieldType":"Number",
			      "tableHeader":"Sales and related occupations",
			      "category":"Occupation",
			      "rowID":157,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_SalesOcc",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"OfficeAdmin",
			      "fieldAlias":"OfficeAdmin",
			      "fieldType":"Number",
			      "tableHeader":"Office and administrative support occupations",
			      "category":"Occupation",
			      "rowID":158,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_OfficeAdmin",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"NatResources",
			      "fieldAlias":"NatResources",
			      "fieldType":"Number",
			      "tableHeader":"Natural resources, construction, and maintenance occupations",
			      "category":"Occupation",
			      "rowID":159,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_NatResources",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"FarmFish",
			      "fieldAlias":"FarmFish",
			      "fieldType":"Number",
			      "tableHeader":"Farming, fishing, and forestry occupations",
			      "category":"Occupation",
			      "rowID":160,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_FarmFish",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"Construction",
			      "fieldAlias":"Construction",
			      "fieldType":"Number",
			      "tableHeader":"Construction and extraction occupations",
			      "category":"Occupation",
			      "rowID":161,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_Construction",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"InstRepair",
			      "fieldAlias":"InstRepair",
			      "fieldType":"Number",
			      "tableHeader":"Installation, maintenance, and repair occupations",
			      "category":"Occupation",
			      "rowID":162,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_InstRepair",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"ProdTransMaterial",
			      "fieldAlias":"ProdTransMaterial",
			      "fieldType":"Number",
			      "tableHeader":"Production, transportation, and material moving occupations",
			      "category":"Occupation",
			      "rowID":163,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_ProdTransMaterial",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"Production",
			      "fieldAlias":"Production",
			      "fieldType":"Number",
			      "tableHeader":"Production occupations",
			      "category":"Occupation",
			      "rowID":164,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_Production",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"Transportation",
			      "fieldAlias":"Transportation",
			      "fieldType":"Number",
			      "tableHeader":"Transportation occupations",
			      "category":"Occupation",
			      "rowID":165,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_Transportation",
			      "class":null,
			      "timePeriod":null
			   },
			   {
			      "fieldName":"MaterialMoving",
			      "fieldAlias":"MaterialMoving",
			      "fieldType":"Number",
			      "tableHeader":"Material moving occupations",
			      "category":"Occupation",
			      "rowID":166,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"Occupation",
			      "chartType":"bubble",
			      "canSum":"TRUE",
			      "dataSource":"",
			      "percentField":"PCT_MaterialMoving",
			      "class":null,
			      "timePeriod":null
			   }
			]
			   
					        }
            return acsFieldsConfig;
        }
    );
}());