(function() {

    "use strict";

    define(

        function() {
            var acsFieldsConfig = new function() {
            var self = this;
			self.fields =
			[
			   {
			      "fieldName":"ACRES",
			      "fieldAlias":"Acres",
			      "fieldType":"Number",
			      "tableHeader":"Acres",
			      "category":"General",
			      "rowID":1,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"SQMI",
			      "fieldAlias":"Square Miles",
			      "fieldType":"Number",
			      "tableHeader":"Square Miles",
			      "category":"General",
			      "rowID":2,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"TOTAL_POP",
			      "fieldAlias":"Total Population",
			      "fieldType":"Number",
			      "tableHeader":"Total Population",
			      "category":"General",
			      "rowID":3,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"TOTAL_MALE",
			      "fieldAlias":"Male Population",
			      "fieldType":"Number",
			      "tableHeader":"Male Population",
			      "category":"Age By Gender",
			      "rowID":18,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"M_Y5LESS5",
			      "fieldAlias":"Males less than 5",
			      "fieldType":"Number",
			      "tableHeader":"Males less than 5",
			      "category":"Age By Gender",
			      "rowID":19,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y5TO9",
			      "fieldAlias":"Males age 5 to 9",
			      "fieldType":"Number",
			      "tableHeader":"Males age 5 to 9",
			      "category":"Age By Gender",
			      "rowID":20,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y10TO14",
			      "fieldAlias":"Males age 10 to 14",
			      "fieldType":"Number",
			      "tableHeader":"Males age 10 to 14",
			      "category":"Age By Gender",
			      "rowID":21,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y15TO17",
			      "fieldAlias":"Males age 15 to 17",
			      "fieldType":"Number",
			      "tableHeader":"Males age 15 to 17",
			      "category":"Age By Gender",
			      "rowID":22,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y18TO19",
			      "fieldAlias":"Males age 18 to 19",
			      "fieldType":"Number",
			      "tableHeader":"Males age 18 to 19",
			      "category":"Age By Gender",
			      "rowID":23,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y20",
			      "fieldAlias":"Males age 20",
			      "fieldType":"Number",
			      "tableHeader":"Males age 20",
			      "category":"Age By Gender",
			      "rowID":24,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y21",
			      "fieldAlias":"Males age 21",
			      "fieldType":"Number",
			      "tableHeader":"Males age 21",
			      "category":"Age By Gender",
			      "rowID":25,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y22TO24",
			      "fieldAlias":"Males age 22 to 24",
			      "fieldType":"Number",
			      "tableHeader":"Males age 22 to 24",
			      "category":"Age By Gender",
			      "rowID":26,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y25TO29",
			      "fieldAlias":"Males age 25 to 29",
			      "fieldType":"Number",
			      "tableHeader":"Males age 25 to 29",
			      "category":"Age By Gender",
			      "rowID":27,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y30TO34",
			      "fieldAlias":"Males age 30 to 34",
			      "fieldType":"Number",
			      "tableHeader":"Males age 30 to 34",
			      "category":"Age By Gender",
			      "rowID":28,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y35TO39",
			      "fieldAlias":"Males age 35 to 39",
			      "fieldType":"Number",
			      "tableHeader":"Males age 35 to 39",
			      "category":"Age By Gender",
			      "rowID":29,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y40TO44",
			      "fieldAlias":"Males age 40 to 44",
			      "fieldType":"Number",
			      "tableHeader":"Males age 40 to 44",
			      "category":"Age By Gender",
			      "rowID":30,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y45TO49",
			      "fieldAlias":"Males age 45 to 49",
			      "fieldType":"Number",
			      "tableHeader":"Males age 45 to 49",
			      "category":"Age By Gender",
			      "rowID":31,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y50TO54",
			      "fieldAlias":"Males age 50 to 54",
			      "fieldType":"Number",
			      "tableHeader":"Males age 50 to 54",
			      "category":"Age By Gender",
			      "rowID":32,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y55TO59",
			      "fieldAlias":"Males age 55 to 59",
			      "fieldType":"Number",
			      "tableHeader":"Males age 55 to 59",
			      "category":"Age By Gender",
			      "rowID":33,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y60TO61",
			      "fieldAlias":"Males age 60 to 61",
			      "fieldType":"Number",
			      "tableHeader":"Males age 60 to 61",
			      "category":"Age By Gender",
			      "rowID":34,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y62TO64",
			      "fieldAlias":"Males age 62 to 64",
			      "fieldType":"Number",
			      "tableHeader":"Males age 62 to 64",
			      "category":"Age By Gender",
			      "rowID":35,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y65TO66",
			      "fieldAlias":"Males age 65 to 66",
			      "fieldType":"Number",
			      "tableHeader":"Males age 65 to 66",
			      "category":"Age By Gender",
			      "rowID":36,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y67TO69",
			      "fieldAlias":"Males age 67 to 69",
			      "fieldType":"Number",
			      "tableHeader":"Males age 67 to 69",
			      "category":"Age By Gender",
			      "rowID":37,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y70TO74",
			      "fieldAlias":"Males age 70 to 74",
			      "fieldType":"Number",
			      "tableHeader":"Males age 70 to 74",
			      "category":"Age By Gender",
			      "rowID":38,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y75TO79",
			      "fieldAlias":"Males age 75 to 79",
			      "fieldType":"Number",
			      "tableHeader":"Males age 75 to 79",
			      "category":"Age By Gender",
			      "rowID":39,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y80TO84",
			      "fieldAlias":"Males age 80 to 84",
			      "fieldType":"Number",
			      "tableHeader":"Males age 80 to 84",
			      "category":"Age By Gender",
			      "rowID":40,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"M_Y85UP",
			      "fieldAlias":"Males age 85 or older",
			      "fieldType":"Number",
			      "tableHeader":"Males age 85 or older",
			      "category":"Age By Gender",
			      "rowID":41,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_MALE"
			   },
			   {
			      "fieldName":"TOTAL_FEMALE",
			      "fieldAlias":"Female Population",
			      "fieldType":"Number",
			      "tableHeader":"Female Population",
			      "category":"Age By Gender",
			      "rowID":42,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"F_Y5LESS5",
			      "fieldAlias":"Females less than 5",
			      "fieldType":"Number",
			      "tableHeader":"Females less than 5",
			      "category":"Age By Gender",
			      "rowID":43,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y5TO9",
			      "fieldAlias":"Females age 5 to 9",
			      "fieldType":"Number",
			      "tableHeader":"Females age 5 to 9",
			      "category":"Age By Gender",
			      "rowID":44,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y10TO14",
			      "fieldAlias":"Females age 10 to 14",
			      "fieldType":"Number",
			      "tableHeader":"Females age 10 to 14",
			      "category":"Age By Gender",
			      "rowID":45,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y15TO17",
			      "fieldAlias":"Females age 15 to 17",
			      "fieldType":"Number",
			      "tableHeader":"Females age 15 to 17",
			      "category":"Age By Gender",
			      "rowID":46,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y18TO19",
			      "fieldAlias":"Females age 18 to 19",
			      "fieldType":"Number",
			      "tableHeader":"Females age 18 to 19",
			      "category":"Age By Gender",
			      "rowID":47,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y20",
			      "fieldAlias":"Females age 20",
			      "fieldType":"Number",
			      "tableHeader":"Females age 20",
			      "category":"Age By Gender",
			      "rowID":48,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y21",
			      "fieldAlias":"Females age 21",
			      "fieldType":"Number",
			      "tableHeader":"Females age 21",
			      "category":"Age By Gender",
			      "rowID":49,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y22TO24",
			      "fieldAlias":"Females age 22 to 24",
			      "fieldType":"Number",
			      "tableHeader":"Females age 22 to 24",
			      "category":"Age By Gender",
			      "rowID":50,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y25TO29",
			      "fieldAlias":"Females age 25 to 29",
			      "fieldType":"Number",
			      "tableHeader":"Females age 25 to 29",
			      "category":"Age By Gender",
			      "rowID":51,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y30TO34",
			      "fieldAlias":"Females age 30 to 34",
			      "fieldType":"Number",
			      "tableHeader":"Females age 30 to 34",
			      "category":"Age By Gender",
			      "rowID":52,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y35TO39",
			      "fieldAlias":"Females age 35 to 39",
			      "fieldType":"Number",
			      "tableHeader":"Females age 35 to 39",
			      "category":"Age By Gender",
			      "rowID":53,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y40TO44",
			      "fieldAlias":"Females age 40 to 44",
			      "fieldType":"Number",
			      "tableHeader":"Females age 40 to 44",
			      "category":"Age By Gender",
			      "rowID":54,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y45TO49",
			      "fieldAlias":"Females age 45 to 49",
			      "fieldType":"Number",
			      "tableHeader":"Females age 45 to 49",
			      "category":"Age By Gender",
			      "rowID":55,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y50TO54",
			      "fieldAlias":"Females age 50 to 54",
			      "fieldType":"Number",
			      "tableHeader":"Females age 50 to 54",
			      "category":"Age By Gender",
			      "rowID":56,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y55TO59",
			      "fieldAlias":"Females age 55 to 59",
			      "fieldType":"Number",
			      "tableHeader":"Females age 55 to 59",
			      "category":"Age By Gender",
			      "rowID":57,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y60TO61",
			      "fieldAlias":"Females age 60 to 61",
			      "fieldType":"Number",
			      "tableHeader":"Females age 60 to 61",
			      "category":"Age By Gender",
			      "rowID":58,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y62TO64",
			      "fieldAlias":"Females age 62 to 64",
			      "fieldType":"Number",
			      "tableHeader":"Females age 62 to 64",
			      "category":"Age By Gender",
			      "rowID":59,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y65TO66",
			      "fieldAlias":"Females age 65 to 66",
			      "fieldType":"Number",
			      "tableHeader":"Females age 65 to 66",
			      "category":"Age By Gender",
			      "rowID":60,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y67TO69",
			      "fieldAlias":"Females age 67 to 69",
			      "fieldType":"Number",
			      "tableHeader":"Females age 67 to 69",
			      "category":"Age By Gender",
			      "rowID":61,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y70TO74",
			      "fieldAlias":"Females age 70 to 74",
			      "fieldType":"Number",
			      "tableHeader":"Females age 70 to 74",
			      "category":"Age By Gender",
			      "rowID":62,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y75TO79",
			      "fieldAlias":"Females age 75 to 79",
			      "fieldType":"Number",
			      "tableHeader":"Females age 75 to 79",
			      "category":"Age By Gender",
			      "rowID":63,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y80TO84",
			      "fieldAlias":"Females age 80 to 84",
			      "fieldType":"Number",
			      "tableHeader":"Females age 80 to 84",
			      "category":"Age By Gender",
			      "rowID":64,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"F_Y85UP",
			      "fieldAlias":"Females age 85 or older",
			      "fieldType":"Number",
			      "tableHeader":"Females age 85 or older",
			      "category":"Age By Gender",
			      "rowID":65,
			      "groupID":"<span class='myHiddenClass'>03</span>Age By Gender",
			      "chartCategory":"Age By Gender",
			      "chartType":"pyramid",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_FEMALE"
			   },
			   {
			      "fieldName":"MgBizSciArt",
			      "fieldAlias":"Management, business, science, and arts occupations",
			      "fieldType":"Number",
			      "tableHeader":"Management, business, science, and arts occupations",
			      "category":"Occupation",
			      "rowID":132,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"MgBizFin",
			      "fieldAlias":"Management, business, and financial occupations",
			      "fieldType":"Number",
			      "tableHeader":"Management, business, and financial occupations",
			      "category":"Occupation",
			      "rowID":133,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "MgBizSciArt",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"Mgmt",
			      "fieldAlias":"Management occupations",
			      "fieldType":"Number",
			      "tableHeader":"Management occupations",
			      "category":"Occupation",
			      "rowID":134,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "MgBizFin",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"BizFin",
			      "fieldAlias":"Business and financial operations occupations",
			      "fieldType":"Number",
			      "tableHeader":"Business and financial operations occupations",
			      "category":"Occupation",
			      "rowID":135,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "MgBizFin",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"CompEngSci",
			      "fieldAlias":"Computer, engineering, and science occupations",
			      "fieldType":"Number",
			      "tableHeader":"Computer, engineering, and science occupations",
			      "category":"Occupation",
			      "rowID":136,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"CompMath",
			      "fieldAlias":"Computer and mathematical occupations",
			      "fieldType":"Number",
			      "tableHeader":"Computer and mathematical occupations",
			      "category":"Occupation",
			      "rowID":137,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "CompEngSci",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"ArchEngin",
			      "fieldAlias":"Architecture and engineering occupations",
			      "fieldType":"Number",
			      "tableHeader":"Architecture and engineering occupations",
			      "category":"Occupation",
			      "rowID":138,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "CompEngSci",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"LifePhysSocSci",
			      "fieldAlias":"Life, physical, and social science occupations",
			      "fieldType":"Number",
			      "tableHeader":"Life, physical, and social science occupations",
			      "category":"Occupation",
			      "rowID":139,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"EduLegComArtMedia",
			      "fieldAlias":"Education, legal, community service, arts, and media occupations",
			      "fieldType":"Number",
			      "tableHeader":"Education, legal, community service, arts, and media occupations",
			      "category":"Occupation",
			      "rowID":140,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"CommSocServ",
			      "fieldAlias":"Community and social service occupations",
			      "fieldType":"Number",
			      "tableHeader":"Community and social service occupations",
			      "category":"Occupation",
			      "rowID":141,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "EduLegComArtMedia",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"Legal",
			      "fieldAlias":"Legal occupations",
			      "fieldType":"Number",
			      "tableHeader":"Legal occupations",
			      "category":"Occupation",
			      "rowID":142,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "EduLegComArtMedia",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"EduTrainLib",
			      "fieldAlias":"Education, training, and library occupations",
			      "fieldType":"Number",
			      "tableHeader":"Education, training, and library occupations",
			      "category":"Occupation",
			      "rowID":143,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "EduLegComArtMedia",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"ArtEntSportMedia",
			      "fieldAlias":"Arts, design, entertainment, sports, and media occupations",
			      "fieldType":"Number",
			      "tableHeader":"Arts, design, entertainment, sports, and media occupations",
			      "category":"Occupation",
			      "rowID":144,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "EduLegComArtMedia",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"HealthTechnical",
			      "fieldAlias":"Healthcare practitioners and technical occupations",
			      "fieldType":"Number",
			      "tableHeader":"Healthcare practitioners and technical occupations",
			      "category":"Occupation",
			      "rowID":145,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"HealthDiagTechOcc",
			      "fieldAlias":"Health diagnosing and treating practitioners and other technical occupations",
			      "fieldType":"Number",
			      "tableHeader":"Health diagnosing and treating practitioners and other technical occupations",
			      "category":"Occupation",
			      "rowID":146,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "HealthTechnical",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"HealthTech",
			      "fieldAlias":"Health technologists and technicians ",
			      "fieldType":"Number",
			      "tableHeader":"Health technologists and technicians ",
			      "category":"Occupation",
			      "rowID":147,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "HealthTechnical",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"ServiceOcc",
			      "fieldAlias":"Service occupations",
			      "fieldType":"Number",
			      "tableHeader":"Service occupations",
			      "category":"Occupation",
			      "rowID":148,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"HealthSupport",
			      "fieldAlias":"Healthcare support occupations",
			      "fieldType":"Number",
			      "tableHeader":"Healthcare support occupations",
			      "category":"Occupation",
			      "rowID":149,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ServiceOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"ProtectiveServ",
			      "fieldAlias":"Protective service occupations",
			      "fieldType":"Number",
			      "tableHeader":"Protective service occupations",
			      "category":"Occupation",
			      "rowID":150,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ServiceOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"Firefighting",
			      "fieldAlias":"Firefighting and prevention, and other protective service workers including supervisors",
			      "fieldType":"Number",
			      "tableHeader":"Firefighting and prevention, and other protective service workers including supervisors",
			      "category":"Occupation",
			      "rowID":151,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ProtectiveServ",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"LawEnforcement",
			      "fieldAlias":"Law enforcement workers including supervisors",
			      "fieldType":"Number",
			      "tableHeader":"Law enforcement workers including supervisors",
			      "category":"Occupation",
			      "rowID":152,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ProtectiveServ",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"FoodPrep",
			      "fieldAlias":"Food preparation and serving related occupations",
			      "fieldType":"Number",
			      "tableHeader":"Food preparation and serving related occupations",
			      "category":"Occupation",
			      "rowID":153,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ServiceOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"GroundsMaint",
			      "fieldAlias":"Building and grounds cleaning and maintenance occupations",
			      "fieldType":"Number",
			      "tableHeader":"Building and grounds cleaning and maintenance occupations",
			      "category":"Occupation",
			      "rowID":154,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ServiceOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"PersonalCare",
			      "fieldAlias":"Personal care and service occupations",
			      "fieldType":"Number",
			      "tableHeader":"Personal care and service occupations",
			      "category":"Occupation",
			      "rowID":155,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ServiceOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"SalesOfficeOcc",
			      "fieldAlias":"Sales and office occupations",
			      "fieldType":"Number",
			      "tableHeader":"Sales and office occupations",
			      "category":"Occupation",
			      "rowID":156,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"SalesOcc",
			      "fieldAlias":"Sales and related occupations",
			      "fieldType":"Number",
			      "tableHeader":"Sales and related occupations",
			      "category":"Occupation",
			      "rowID":157,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "SalesOfficeOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"OfficeAdmin",
			      "fieldAlias":"Office and administrative support occupations",
			      "fieldType":"Number",
			      "tableHeader":"Office and administrative support occupations",
			      "category":"Occupation",
			      "rowID":158,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "SalesOfficeOcc",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"NatResources",
			      "fieldAlias":"Natural resources, construction, and maintenance occupations",
			      "fieldType":"Number",
			      "tableHeader":"Natural resources, construction, and maintenance occupations",
			      "category":"Occupation",
			      "rowID":159,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"FarmFish",
			      "fieldAlias":"Farming, fishing, and forestry occupations",
			      "fieldType":"Number",
			      "tableHeader":"Farming, fishing, and forestry occupations",
			      "category":"Occupation",
			      "rowID":160,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "NatResources",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"Construction",
			      "fieldAlias":"Construction and extraction occupations",
			      "fieldType":"Number",
			      "tableHeader":"Construction and extraction occupations",
			      "category":"Occupation",
			      "rowID":161,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "NatResources",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"InstRepair",
			      "fieldAlias":"Installation, maintenance, and repair occupations",
			      "fieldType":"Number",
			      "tableHeader":"Installation, maintenance, and repair occupations",
			      "category":"Occupation",
			      "rowID":162,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "NatResources",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"ProdTransMaterial",
			      "fieldAlias":"Production, transportation, and material moving occupations",
			      "fieldType":"Number",
			      "tableHeader":"Production, transportation, and material moving occupations",
			      "category":"Occupation",
			      "rowID":163,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"Production",
			      "fieldAlias":"Production occupations",
			      "fieldType":"Number",
			      "tableHeader":"Production occupations",
			      "category":"Occupation",
			      "rowID":164,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ProdTransMaterial",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"Transportation",
			      "fieldAlias":"Transportation occupations",
			      "fieldType":"Number",
			      "tableHeader":"Transportation occupations",
			      "category":"Occupation",
			      "rowID":165,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ProdTransMaterial",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"MaterialMoving",
			      "fieldAlias":"Material moving occupations",
			      "fieldType":"Number",
			      "tableHeader":"Material moving occupations",
			      "category":"Occupation",
			      "rowID":166,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"funnel",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "ProdTransMaterial",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"MEDIAN_AGE",
			      "fieldAlias":"Median Age",
			      "fieldType":"Number",
			      "tableHeader":"Median Age",
			      "category":"Age",
			      "rowID":4,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"UNDER5",
			      "fieldAlias":"Under 5",
			      "fieldType":"Number",
			      "tableHeader":"Under 5",
			      "category":"Age",
			      "rowID":5,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"

			   },
			   {
			      "fieldName":"AGE5TO17",
			      "fieldAlias":"5 to 17",
			      "fieldType":"Number",
			      "tableHeader":"5 to 17",
			      "category":"Age",
			      "rowID":6,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE18TO34",
			      "fieldAlias":"18 to 34",
			      "fieldType":"Number",
			      "tableHeader":"18 to 34",
			      "category":"Age",
			      "rowID":7,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE35TO49",
			      "fieldAlias":"35 to 49",
			      "fieldType":"Number",
			      "tableHeader":"35 to 49",
			      "category":"Age",
			      "rowID":8,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE50TO64",
			      "fieldAlias":"50 to 64",
			      "fieldType":"Number",
			      "tableHeader":"50 to 64",
			      "category":"Age",
			      "rowID":9,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE65TO84",
			      "fieldAlias":"65 to 84",
			      "fieldType":"Number",
			      "tableHeader":"65 to 84",
			      "category":"Age",
			      "rowID":10,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE85PLUS",
			      "fieldAlias":"85 and over",
			      "fieldType":"Number",
			      "tableHeader":"85 and over",
			      "category":"Age",
			      "rowID":11,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE25PLUS",
			      "fieldAlias":"25 and over",
			      "fieldType":"Number",
			      "tableHeader":"25 and over",
			      "category":"Age",
			      "rowID":12,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE50PLUS",
			      "fieldAlias":"50 and over",
			      "fieldType":"Number",
			      "tableHeader":"50 and over",
			      "category":"Age",
			      "rowID":13,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE60PLUS",
			      "fieldAlias":"60 and over",
			      "fieldType":"Number",
			      "tableHeader":"60 and over",
			      "category":"Age",
			      "rowID":14,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE65PLUS",
			      "fieldAlias":"65 and over",
			      "fieldType":"Number",
			      "tableHeader":"65 and over",
			      "category":"Age",
			      "rowID":15,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE70PLUS",
			      "fieldAlias":"70 and over",
			      "fieldType":"Number",
			      "tableHeader":"70 and over",
			      "category":"Age",
			      "rowID":16,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"AGE75PLUS",
			      "fieldAlias":"75 and over",
			      "fieldType":"Number",
			      "tableHeader":"75 and over",
			      "category":"Age",
			      "rowID":17,
			      "groupID":"<span class='myHiddenClass'>02</span>Age",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"WHITE",
			      "fieldAlias":"White",
			      "fieldType":"Number",
			      "tableHeader":"White, NH",
			      "category":"Race",
			      "rowID":66,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"ACS 2014",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"BLACK",
			      "fieldAlias":"Black",
			      "fieldType":"Number",
			      "tableHeader":"Black, NH",
			      "category":"Race",
			      "rowID":67,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"NATIVE",
			      "fieldAlias":"Native American",
			      "fieldType":"Number",
			      "tableHeader":"Native American, NH",
			      "category":"Race",
			      "rowID":68,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"ASIAN",
			      "fieldAlias":"Asian",
			      "fieldType":"Number",
			      "tableHeader":"Asian, NH",
			      "category":"Race",
			      "rowID":69,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"PACIFIC",
			      "fieldAlias":"Pacific Islander",
			      "fieldType":"Number",
			      "tableHeader":"Pacific Islander, NH",
			      "category":"Race",
			      "rowID":70,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"OTHER",
			      "fieldAlias":"Other",
			      "fieldType":"Number",
			      "tableHeader":"Other, NH",
			      "category":"Race",
			      "rowID":71,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"TWO_OR_MORE",
			      "fieldAlias":"Two or More",
			      "fieldType":"Number",
			      "tableHeader":"Two or More, NH",
			      "category":"Race",
			      "rowID":72,
			      "groupID":"<span class='myHiddenClass'>04</span>Population by Race",
			      "chartCategory":"Race",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"HISPANIC",
			      "fieldAlias":"Hispanic",
			      "fieldType":"Number",
			      "tableHeader":"Hispanic",
			      "category":"Ethnicity",
			      "rowID":73,
			      "groupID":"<span class='myHiddenClass'>05</span>Population by Ethnicity",
			      "chartCategory":"Ethnicity",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"NOT_HISPANIC",
			      "fieldAlias":"Non-Hispanic",
			      "fieldType":"Number",
			      "tableHeader":"Non-Hispanic",
			      "category":"Ethnicity",
			      "rowID":74,
			      "groupID":"<span class='myHiddenClass'>05</span>Population by Ethnicity",
			      "chartCategory":"Ethnicity",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"MINORITY_POP",
			      "fieldAlias":"Minority Population",
			      "fieldType":"Number",
			      "tableHeader":"Minority Population",
			      "category":"General",
			      "rowID":75,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"TOTAL_FAMILIES",
			      "fieldAlias":"Total Families",
			      "fieldType":"Number",
			      "tableHeader":"Total Families",
			      "category":"General",
			      "rowID":76,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": ""
			   },
			   {
			      "fieldName":"TOTAL_HOUSEHOLDS",
			      "fieldAlias":"Total Households",
			      "fieldType":"Number",
			      "tableHeader":"Total Households",
			      "category":"Housholds",
			      "rowID":77,
			      "groupID":"<span class='myHiddenClass'>06</span>Households",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"AVG_HH_SIZE",
			      "fieldAlias":"Average Household Size",
			      "fieldType":"Number",
			      "tableHeader":"Average Household Size",
			      "category":"Housholds",
			      "rowID":78,
			      "groupID":"<span class='myHiddenClass'>06</span>Households",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"LINGLSO_HH",
			      "fieldAlias":"Linguistically Isolated Households",
			      "fieldType":"Number",
			      "tableHeader":"Linguistically Isolated Households",
			      "category":"Housholds",
			      "rowID":79,
			      "groupID":"<span class='myHiddenClass'>06</span>Households",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"MEDIAN_HOUSEHOLD_INCOME",
			      "fieldAlias":"Median Household Income",
			      "fieldType":"Currency",
			      "tableHeader":"Median Household Income",
			      "category":"Houshold Income",
			      "rowID":80,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"PER_CAPITA_INCOME",
			      "fieldAlias":"Per Capita Income",
			      "fieldType":"Currency",
			      "tableHeader":"Per Capita Income",
			      "category":"Houshold Income",
			      "rowID":81,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"INCOME_BELOW_POVERTY_LEVEL",
			      "fieldAlias":"Below Poverty Level",
			      "fieldType":"Number",
			      "tableHeader":"Below Poverty Level",
			      "category":"Houshold Income",
			      "rowID":82,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Poverty Level",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"INCOME_NOT_BELOW_POVERTY_LEVEL",
			      "fieldAlias":"Above Poverty Level",
			      "fieldType":"Number",
			      "tableHeader":"Above Poverty Level",
			      "category":"Houshold Income",
			      "rowID":83,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Poverty Level",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"HH_LESS_THAN_25K",
			      "fieldAlias":"Less Than 25K",
			      "fieldType":"Number",
			      "tableHeader":"Household Income Less Than 25K",
			      "category":"Houshold Income",
			      "rowID":84,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"HH_25K_TO_49K",
			      "fieldAlias":"25K To 49K",
			      "fieldType":"Number",
			      "tableHeader":"Household Income 25K To 49K",
			      "category":"Houshold Income",
			      "rowID":85,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"HH_50K_TO_99K",
			      "fieldAlias":"50K To 99K",
			      "fieldType":"Number",
			      "tableHeader":"Household Income 50K To 99K",
			      "category":"Houshold Income",
			      "rowID":86,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"HH_100K_PLUS",
			      "fieldAlias":"100K Plus",
			      "fieldType":"Number",
			      "tableHeader":"Household Income 100K Plus",
			      "category":"Houshold Income",
			      "rowID":87,
			      "groupID":"<span class='myHiddenClass'>07</span>Household Income",
			      "chartCategory":"Houshold Income",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HOUSEHOLDS"
			   },
			   {
			      "fieldName":"TOTAL_HU",
			      "fieldAlias":"Total Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Total Housing Units",
			      "category":"Housing Units",
			      "rowID":88,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"OCCUPIED_HU",
			      "fieldAlias":"Total Occupied Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Total Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":89,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"OCCUPIED_HU",
			      "fieldAlias":"Occupied Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":90,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Occupancy",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HU"
			   },
			   {
			      "fieldName":"VACANT_HU",
			      "fieldAlias":"Vacant Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Vacant Housing Units",
			      "category":"Housing Units",
			      "rowID":91,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Occupancy",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HU"
			   },
			   {
			      "fieldName":"SEASONAL_HU",
			      "fieldAlias":"Seasonal Housing",
			      "fieldType":"Number",
			      "tableHeader":"Seasonal Housing Units",
			      "category":"Housing Units",
			      "rowID":92,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Seasonal Housing",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HU"
			   },
			   {
			      "fieldName":"NON_SEASONAL_HU",
			      "fieldAlias":"Non-Seasonal Housing",
			      "fieldType":"Number",
			      "tableHeader":"Non-Seasonal Housing Units",
			      "category":"Housing Units",
			      "rowID":93,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Seasonal Housing",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HU"
			   },
			   {
			      "fieldName":"NON_SEASONAL_VACANT_HU",
			      "fieldAlias":"Non-Seasonal Vacant Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Non-Seasonal Vacant Housing Units",
			      "category":"Housing Units",
			      "rowID":94,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"OWNER_OCC_HU",
			      "fieldAlias":"Owner Occupied",
			      "fieldType":"Number",
			      "tableHeader":"Owner Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":95,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Occupied Status",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HU"
			   },
			   {
			      "fieldName":"RENTER_OCC_HU",
			      "fieldAlias":"Renter Occupied",
			      "fieldType":"Number",
			      "tableHeader":"Renter Occupied Housing Units",
			      "category":"Housing Units",
			      "rowID":96,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"Occupied Status",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_HU"
			   },
			   {
			      "fieldName":"AVG_HH_SIZE_OWNER_HU",
			      "fieldAlias":"Avgerage Household Size Owner Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Avgerage Household Size Owner Housing Units",
			      "category":"Housing Units",
			      "rowID":97,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"AVG_HH_SIZE_RENTER_HU",
			      "fieldAlias":"Average Houshold Size Renter Housing Units",
			      "fieldType":"Number",
			      "tableHeader":"Average Houshold Size Renter Housing Units",
			      "category":"Housing Units",
			      "rowID":98,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"VACANCY_RATE",
			      "fieldAlias":"Vacancy Rate",
			      "fieldType":"Number",
			      "tableHeader":"Vacancy Rate",
			      "category":"Housing Units",
			      "rowID":99,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"SEASONAL_VACANCY_RATE",
			      "fieldAlias":"Seasonal Vacancy Rate",
			      "fieldType":"Number",
			      "tableHeader":"Seasonal Vacancy Rate",
			      "category":"Housing Units",
			      "rowID":100,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"NON_SEASONAL_VACANCY_RATE",
			      "fieldAlias":"Non-Seasonal Vacancy Rate",
			      "fieldType":"Number",
			      "tableHeader":"Non Seasonal Vacancy Rate",
			      "category":"Housing Units",
			      "rowID":101,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"MEDIAN_VALUE",
			      "fieldAlias":"Median Value",
			      "fieldType":"Currency",
			      "tableHeader":"Median Value",
			      "category":"Housing Units",
			      "rowID":102,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"MEDIAN_GROSS_RENT",
			      "fieldAlias":"Median Gross Rent",
			      "fieldType":"Currency",
			      "tableHeader":"Median Gross Rent",
			      "category":"Housing Units",
			      "rowID":103,
			      "groupID":"<span class='myHiddenClass'>08</span>Housing Units",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":false,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": ""
			   },
			   {
			      "fieldName":"LT9GRADE",
			      "fieldAlias":"Less than 9th Grade",
			      "fieldType":"Number",
			      "tableHeader":"Less than 9th Grade",
			      "category":"Education",
			      "rowID":104,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"NOHSDIPLOMA",
			      "fieldAlias":"No High School Diploma",
			      "fieldType":"Number",
			      "tableHeader":"No High School Diploma",
			      "category":"Education",
			      "rowID":105,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"HSGRAD",
			      "fieldAlias":"High School Graduate",
			      "fieldType":"Number",
			      "tableHeader":"High School Graduate",
			      "category":"Education",
			      "rowID":106,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"SOMECOLLEGE",
			      "fieldAlias":"Some College",
			      "fieldType":"Number",
			      "tableHeader":"Some College",
			      "category":"Education",
			      "rowID":107,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"ASSOCIATES",
			      "fieldAlias":"Associates",
			      "fieldType":"Number",
			      "tableHeader":"Associates",
			      "category":"Education",
			      "rowID":108,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"BACHELORS",
			      "fieldAlias":"Bachelors",
			      "fieldType":"Number",
			      "tableHeader":"Bachelors",
			      "category":"Education",
			      "rowID":109,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"GRADPROF",
			      "fieldAlias":"Graduate / Professional",
			      "fieldType":"Number",
			      "tableHeader":"Graduate / Professional",
			      "category":"Education",
			      "rowID":110,
			      "groupID":"<span class='myHiddenClass'>09</span>Education",
			      "chartCategory":"Education",
			      "chartType":"column",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "AGE25PLUS"
			   },
			   {
			      "fieldName":"TOTAL_WORKERS_16PLUS",
			      "fieldAlias":"Total Workers 16 Plus",
			      "fieldType":"Number",
			      "tableHeader":"Total Workers 16 Plus",
			      "category":"Occupation",
			      "rowID":111,
			      "groupID":"<span class='myHiddenClass'>11</span>Occupation",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "false"
			   },
			   {
			      "fieldName":"CIVPOP16PLUS",
			      "fieldAlias":"Civilian Population 16 Plus",
			      "fieldType":"Number",
			      "tableHeader":"Civilian Population 16 Plus",
			      "category":"General",
			      "rowID":112,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"CIVPOP18PLUS",
			      "fieldAlias":"Civilian Population 18 Plus",
			      "fieldType":"Number",
			      "tableHeader":"Civilian Population 18 Plus",
			      "category":"General",
			      "rowID":113,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"VETERAN",
			      "fieldAlias":"Veteran",
			      "fieldType":"Number",
			      "tableHeader":"Veterans",
			      "category":"General",
			      "rowID":114,
			      "groupID":"<span class='myHiddenClass'>01</span>General",
			      "chartCategory":"",
			      "chartType":"",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_POP"
			   },
			   {
			      "fieldName":"CAR_TRUCK_VAN",
			      "fieldAlias":"Car Truck Van",
			      "fieldType":"Number",
			      "tableHeader":"Car Truck Van",
			      "category":"Modes of Transportation",
			      "rowID":115,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"DROVE_ALONE",
			      "fieldAlias":"Drove Alone",
			      "fieldType":"Number",
			      "tableHeader":"Drove Alone",
			      "category":"Modes of Transportation",
			      "rowID":116,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"CARPOOLED",
			      "fieldAlias":"Carpooled",
			      "fieldType":"Number",
			      "tableHeader":"Carpooled",
			      "category":"Modes of Transportation",
			      "rowID":117,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"BUS",
			      "fieldAlias":"Bus",
			      "fieldType":"Number",
			      "tableHeader":"Bus",
			      "category":"Modes of Transportation",
			      "rowID":118,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"RAIL",
			      "fieldAlias":"Rail",
			      "fieldType":"Number",
			      "tableHeader":"Rail",
			      "category":"Modes of Transportation",
			      "rowID":119,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"TAXI",
			      "fieldAlias":"Taxi",
			      "fieldType":"Number",
			      "tableHeader":"Taxi",
			      "category":"Modes of Transportation",
			      "rowID":120,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"MOTORCYCLE",
			      "fieldAlias":"Motorcycle",
			      "fieldType":"Number",
			      "tableHeader":"Motorcycle",
			      "category":"Modes of Transportation",
			      "rowID":121,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"BICYCLE",
			      "fieldAlias":"Bicycle",
			      "fieldType":"Number",
			      "tableHeader":"Bicycle",
			      "category":"Modes of Transportation",
			      "rowID":122,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"WALKED",
			      "fieldAlias":"Walked",
			      "fieldType":"Number",
			      "tableHeader":"Walked",
			      "category":"Modes of Transportation",
			      "rowID":123,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"OTHER_MEANS",
			      "fieldAlias":"Other Means",
			      "fieldType":"Number",
			      "tableHeader":"Other Means",
			      "category":"Modes of Transportation",
			      "rowID":124,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"WORKED_FROM_HOME",
			      "fieldAlias":"Worked from Home",
			      "fieldType":"Number",
			      "tableHeader":"Worked from Home",
			      "category":"Modes of Transportation",
			      "rowID":125,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Modes of Transportation",
			      "chartType":"pie",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "TOTAL_WORKERS_16PLUS"
			   },
			   {
			      "fieldName":"NO_VEHICLE",
			      "fieldAlias":"No Vehicle",
			      "fieldType":"Number",
			      "tableHeader":"No Vehicle",
			      "category":"Modes of Transportation",
			      "rowID":126,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Vehicle Count",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "OCCUPIED_HU"
			   },
			   {
			      "fieldName":"ONE_VEHICLE",
			      "fieldAlias":"One Vehicle",
			      "fieldType":"Number",
			      "tableHeader":"One Vehicle",
			      "category":"Modes of Transportation",
			      "rowID":127,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Vehicle Count",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "OCCUPIED_HU"
			   },
			   {
			      "fieldName":"TWO_VEHICLES",
			      "fieldAlias":"Two Vehicles",
			      "fieldType":"Number",
			      "tableHeader":"Two Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":128,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Vehicle Count",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "OCCUPIED_HU"
			   },
			   {
			      "fieldName":"THREE_VEHICLES",
			      "fieldAlias":"Three Vehicles",
			      "fieldType":"Number",
			      "tableHeader":"Three Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":129,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Vehicle Count",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "OCCUPIED_HU"
			   },
			   {
			      "fieldName":"FOUR_VEHICLES",
			      "fieldAlias":"Four Vehicles",
			      "fieldType":"Number",
			      "tableHeader":"Four Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":130,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Vehicle Count",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "OCCUPIED_HU"
			   },
			   {
			      "fieldName":"FIVE_PLUS_VEHICLES",
			      "fieldAlias":"Five Plus Vehicles",
			      "fieldType":"Number",
			      "tableHeader":"Five Plus Vehicles",
			      "category":"Modes of Transportation",
			      "rowID":131,
			      "groupID":"<span class='myHiddenClass'>10</span>Modes of Transportation",
			      "chartCategory":"Vehicle Count",
			      "chartType":"bar",
			      "canSum":true,
			      "dataSource":"",
			      "class":null,
			      "timePeriod":null,
			      "parentField": "",
			      "percentOfField": "OCCUPIED_HU"
			   }
			]

					        }
            return acsFieldsConfig;
        }
    );
}());