(function() {

    "use strict";

    define(

        function() {
            var cbrConfig = new function() {
                var self = this;
                self.mapServices = {
                    ACS2015byBlockGroup: appConfig.layerInfo[7].url
                };

                self.thematicMaps = [{
                        "NodeType": "cat",
                        "Name": "General",
                        "ShortName": "General",
                        "Description": "",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Total Population",
                            "ShortName": "Total Population",
                            "Service": "ACS2015byBlockGroup",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "TOTAL_POP",
                            "Type": "number",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Total Population Per Sq Mile",
                            "ShortName": "Total Population Per Sq Mile",
                            "Service": "ACS2015byBlockGroup",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "POPPERSQMI",
                            "Type": "number",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Age",
                        "ShortName": "Age",
                        "Description": "Population by Age",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent 18 years and over",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% 18 years and over",
                            "DefaultColorRamp": "YlGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_AGE18PLUS",
                            "Type": "percent",
                            "AsPercentages": true,
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent 21 years and over",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% 21 years and over",
                            "DefaultColorRamp": "YlGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_AGE_21PLUS",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent 62 years and over",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% 62 years and over",
                            "DefaultColorRamp": "YlGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_AGE_62PLUS",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent 65 years and over",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% 65 years and over",
                            "DefaultColorRamp": "YlGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_AGE_65PLUS",
                            "AsPercentages": true,
                            "Type": "percent"
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Race and Ethnicity",
                        "ShortName": "Race and Ethnicity",
                        "Description": "...",
                        "items": [ {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Hispanic",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Hispanic",
                            "DefaultColorRamp": "GnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent White",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% White Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_WHITE_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Black",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Black Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_BLACK_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Asian",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Asian Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_ASIAN_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Native American",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Native American Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_NATIVE_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Pacific Islander",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Pacific Islander Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_PACIFIC_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Two Or More Races",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Two or More Races  Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_TWO_OR_MORE_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Other Race",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Other Race Non-Hispanic",
                            "DefaultColorRamp": "YlGnBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_OTHER_NON_HISPANIC",
                            "AsPercentages": true,
                            "Type": "percent"
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Educational Attainment",
                        "ShortName": "Educational Attainment",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population with Education Less than 9th Grade",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Less than 9th Grade",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_LT9GRADE",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population with Education 9th to 12th Grade",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% 9th to 12th Grade",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_NOHSDIPLOMA",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population High School Graduates",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% High School / GED",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_HSGRAD",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population with Some College",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Some College",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_SOMECOLLEGE",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population with Associates Degree",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Associates Degree",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_ASSOCIATES",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population with Bachelors Degree",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Bachelors Degree",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_BACHELORS",
                            "AsPercentages": true,
                            "Type": "percent"
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent of Population with Graduate or Professional Degree",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Graduate or Professional Degree",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_GRADPROF",
                            "AsPercentages": true,
                            "Type": "percent"
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Ability to Speak English",
                        "ShortName": "Ability to Speak English",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Limited English Proficiency (LEP)",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Limited English Proficiency (LEP)",
                            "DefaultColorRamp": "PuBu",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_LIMITED_ENG_PROF",
                            "AsPercentages": true,
                            "Type": "percent",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Veteran Status",
                        "ShortName": "Veteran Status",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Civilian veterans",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Civilian veterans",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_VETERANS",
                            "AsPercentages": true,
                            "Type": "percent",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Households",
                        "ShortName": "Households",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Average Household Size",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "Average Household Size",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "AVG_HH_SIZE",
                            "Type": "number",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Household Income (in 2015 inflation-adjusted dollars)",
                        "ShortName": "Household Income (in 2015 inflation-adjusted dollars)",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Median Household Income (dollars)",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "Median Household Income (dollars)",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "MEDIAN_HOUSEHOLD_INCOME",
                            "Type": "number",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Poverty Status for Persons in the Past 12 Months",
                        "ShortName": "Poverty Status for Persons in the Past 12 Months",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent below poverty level",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Below poverty level",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_INCOME_BELOW_POVERTY",
                            "AsPercentages": true,
                            "Type": "percent",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Commuting to Work",
                        "ShortName": "Commuting to Work",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Car or Truck - drive alone",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Car or Truck - drive alone",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_DROVE_ALONE",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Car or Truck - carpool",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Car or Truck - carpool",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_CARPOOLED",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Public Transportation",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Public Transportation",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_PUBLIC_TRANSPORTATION",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Bicycle",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Bicycle",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_BICYCLE",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Walked",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Walked",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_WALKED",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Other means (taxicab, motorcycle, etc.)",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Other means (taxicab, motorcycle, etc.)",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_TAXI_MOTORCYCLE_OR_OTHER",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Work at home",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Work at home",
                            "DefaultColorRamp": "PuBuGn",
                            "DefaultColorScheme": "Sequential",
                            "Description": "",
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_WORKED_FROM_HOME",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Occupation",
                        "ShortName": "Occupation",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Management, business, science, and arts occupations",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Management, business, science, and arts occupations",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_MGBIZSCIART",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Service occupations",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Service occupations",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_SERVICEOCC",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Sales and office occupations",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Sales and office occupations",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_SALESOFFICEOCC",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Natural resources, construction, and maintenance occupations",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Natural resources, construction, and maintenance occupations",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_NATRESOURCES",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Production, transportation, and material moving occupations",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Production, transportation, and material moving occupations",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_PRODTRANSMATERIAL",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Housing",
                        "ShortName": "Housing",
                        "Description": "Contain housing units related variables",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Total Housing Units",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "Total Housing Units",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "TOTAL_HOUSING_UNITS",
                            "Type": "number",
                            // "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Occupancy, Tenure, Value, and Rent",
                        "ShortName": "Occupancy, Tenure, Value, and Rent",
                        "Description": "Contain housing units related variables",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Occupied Housing Units",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Occupied Housing Units",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_OCCUPIED_HU",
                            "AsPercentages": true,
                            "Type": "percent",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "Percent Vacant Housing Units",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Vacant Housing Units",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_VACANT_HU",
                            "AsPercentages": true,
                            "Type": "percent",
                            "Placeholder": 100000000
                        }]
                    }, {
                        "NodeType": "cat",
                        "Name": "Vehicles Available",
                        "ShortName": "Vehicles Available",
                        "Description": "...",
                        "items": [{
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% No Vehicle Available",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% No Vehicle Available",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_NO_VEHICLE",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% One Vehicle Available",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% One Vehicle Available",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_ONE_VEHICLE",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Two Vehicles Available",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Two Vehicles Available",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_TWO_VEHICLES",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }, {
                            "NodeType": "map",
                            "LayerId": 0,
                            "Name": "% Three or More Vehicles Available",
                            "Service": "ACS2015byBlockGroup",
                            "ShortName": "% Three or More Vehicles Available",
                            "DefaultColorRamp": "OrRd",
                            "DefaultColorScheme": "Sequential",
                            "Description": null,
                            "Source": "American Community Survey 2011-2015 5yr",
                            "FieldName": "PCT_THREE_PLUS_VEHICLES",
                            "Type": "percent",
                            "AsPercentages": "TRUE",
                            "Placeholder": 100000000
                        }]
                    }

                ];
            };
            return cbrConfig;
        });
}());
