(function() {

    "use strict";

    define(

        function() {
            var censusFieldsConfig = new function() {
            var self = this;
			self.fields = 
					[
					   {
					      "fieldName":"ACRES",
					      "fieldAlias":"ACRES",
					      "fieldType":"Number",
					      "tableHeader":"Total Acres",
					      "category":"General",
					      "rowID":1,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"SQMI",
					      "fieldAlias":"SQMI",
					      "fieldType":"Number",
					      "tableHeader":"Total Square Miles",
					      "category":"General",
					      "rowID":2,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"TOTAL_POP",
					      "fieldAlias":"TOTAL_POP",
					      "fieldType":"Number",
					      "tableHeader":"Total Population",
					      "category":"General",
					      "rowID":3,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"MEDIAN_AGE",
					      "fieldAlias":"MEDIAN_AGE",
					      "fieldType":"Number",
					      "tableHeader":"Median Age",
					      "category":"Age",
					      "rowID":4,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":false,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"UNDER5",
					      "fieldAlias":"Under 5",
					      "fieldType":"Number",
					      "tableHeader":"Under 5",
					      "category":"Age",
					      "rowID":5,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_UNDER5",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE5TO17",
					      "fieldAlias":"5 to 17",
					      "fieldType":"Number",
					      "tableHeader":"5 to 17",
					      "category":"Age",
					      "rowID":6,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_5TO17",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE18TO34",
					      "fieldAlias":"18 to 34",
					      "fieldType":"Number",
					      "tableHeader":"18 to 34",
					      "category":"Age",
					      "rowID":7,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_18TO34",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE35TO49",
					      "fieldAlias":"35 to 49",
					      "fieldType":"Number",
					      "tableHeader":"35 to 49",
					      "category":"Age",
					      "rowID":8,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_35TO49",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE50TO64",
					      "fieldAlias":"50 to 64",
					      "fieldType":"Number",
					      "tableHeader":"50 to 64",
					      "category":"Age",
					      "rowID":9,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_50TO64",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE65TO84",
					      "fieldAlias":"65 to 84",
					      "fieldType":"Number",
					      "tableHeader":"65 to 84",
					      "category":"Age",
					      "rowID":10,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_65TO84",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE85PLUS",
					      "fieldAlias":"85 and over",
					      "fieldType":"Number",
					      "tableHeader":"85 and over",
					      "category":"Age",
					      "rowID":11,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"bar",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_85PLUS",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE50PLUS",
					      "fieldAlias":"50 and over",
					      "fieldType":"Number",
					      "tableHeader":"50 and over",
					      "category":"Age",
					      "rowID":12,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_50PLUS",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE60PLUS",
					      "fieldAlias":"AGE60PLUS",
					      "fieldType":"Number",
					      "tableHeader":"60 and over",
					      "category":"Age",
					      "rowID":13,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_60PLUS",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE65PLUS",
					      "fieldAlias":"65 and over",
					      "fieldType":"Number",
					      "tableHeader":"65 and over",
					      "category":"Age",
					      "rowID":14,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_65PLUS",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE70PLUS",
					      "fieldAlias":"70 and over",
					      "fieldType":"Number",
					      "tableHeader":"70 and over",
					      "category":"Age",
					      "rowID":15,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_70PLUS",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"AGE75PLUS",
					      "fieldAlias":"75 and over",
					      "fieldType":"Number",
					      "tableHeader":"75 and over",
					      "category":"Age",
					      "rowID":16,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_75PLUS",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"WHITE",
					      "fieldAlias":"White",
					      "fieldType":"Number",
					      "tableHeader":"White, NH",
					      "category":"Population by Race",
					      "rowID":17,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_WHITE",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"BLACK",
					      "fieldAlias":"Black",
					      "fieldType":"Number",
					      "tableHeader":"Black, NH",
					      "category":"Population by Race",
					      "rowID":18,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_BLACK",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"NATIVE",
					      "fieldAlias":"Native American",
					      "fieldType":"Number",
					      "tableHeader":"Native American, NH",
					      "category":"Population by Race",
					      "rowID":19,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_NATIVE",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"ASIAN",
					      "fieldAlias":"Asian",
					      "fieldType":"Number",
					      "tableHeader":"Asian, NH",
					      "category":"Population by Race",
					      "rowID":20,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_ASIAN",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"PACIFIC",
					      "fieldAlias":"Pacific Islander",
					      "fieldType":"Number",
					      "tableHeader":"Pacific Islander, NH",
					      "category":"Population by Race",
					      "rowID":21,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_PACIFIC",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"OTHER",
					      "fieldAlias":"Other",
					      "fieldType":"Number",
					      "tableHeader":"Other Race, NH",
					      "category":"Population by Race",
					      "rowID":22,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_OTHER",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"TWO_OR_MORE",
					      "fieldAlias":"Two or More",
					      "fieldType":"Number",
					      "tableHeader":"Two or More, NH",
					      "category":"Population by Race",
					      "rowID":23,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_TWO_OR_MORE",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"HISPANIC",
					      "fieldAlias":"Hispanic",
					      "fieldType":"Number",
					      "tableHeader":"Hispanic",
					      "category":"Population by Ethnicity",
					      "rowID":24,
					      "groupID":"<span class='myHiddenClass'>04</span>Population by Ethnicity",
					      "chartCategory":"Population by Ethnicity",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_HISPANIC",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"NOT_HISPANIC",
					      "fieldAlias":"Non-Hispanic",
					      "fieldType":"Number",
					      "tableHeader":"Non-Hispanic",
					      "category":"Population by Ethnicity",
					      "rowID":25,
					      "groupID":"<span class='myHiddenClass'>04</span>Population by Ethnicity",
					      "chartCategory":"Population by Ethnicity",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_NOT_HISPANIC",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"MINORITY_POP",
					      "fieldAlias":"MINORITY_POP",
					      "fieldType":"Number",
					      "tableHeader":"Minority Population",
					      "category":"General",
					      "rowID":26,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_MINORITY_POP",
					      "percentOfField": "TOTAL_POP"
					   },
					   {
					      "fieldName":"TOTAL_HU",
					      "fieldAlias":"TOTAL_HU",
					      "fieldType":"Number",
					      "tableHeader":"Housing Units",
					      "category":"Housing",
					      "rowID":27,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"VACANCY_RATE"
					   },
					   {
					      "fieldName":"OCCUPIED_HU",
					      "fieldAlias":"OCCUPIED_HU",
					      "fieldType":"Number",
					      "tableHeader":"Occupied Housing Units",
					      "category":"Housing",
					      "rowID":28,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_SEASONAL_HU",
					      "percentOfField": "TOTAL_HU"

					   },
					   {
					      "fieldName":"VACANT_HU",
					      "fieldAlias":"VACANT_HU",
					      "fieldType":"Number",
					      "tableHeader":"Vacant Housing Units",
					      "category":"Housing",
					      "rowID":29,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"NON_SEASONAL_VACANCY_RATE",
					      "percentOfField": "TOTAL_HU"
					   },
					   {
					      "fieldName":"SEASONAL_HU",
					      "fieldAlias":"SEASONAL_HU",
					      "fieldType":"Number",
					      "tableHeader":"Seasonal Housing Units",
					      "category":"Housing",
					      "rowID":30,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"",
					      "percentOfField": "TOTAL_HU"
					   },
					   {
					      "fieldName":"NON_SEASONAL_HU",
					      "fieldAlias":"NON_SEASONAL_HU",
					      "fieldType":"Number",
					      "tableHeader":"Non-Seasonal Housing Units",
					      "category":"Housing",
					      "rowID":31,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"",
					      "percentOfField": "TOTAL_HU"
					   },
					   {
					      "fieldName":"NON_SEASONAL_VACANT_HU",
					      "fieldAlias":"NON_SEASONAL_VACANT_HU",
					      "fieldType":"Number",
					      "tableHeader":"Non-Seasonal Vacant Housing Units",
					      "category":"Housing",
					      "rowID":32,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentOfField": "TOTAL_HU"
					   },
					   {
					      "fieldName":"OWNER_OCC_HU",
					      "fieldAlias":"OWNER_OCC_HU",
					      "fieldType":"Number",
					      "tableHeader":"Owner-Occupied Housing Units",
					      "category":"Housing",
					      "rowID":33,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_RENTER_OCCUPIED_HU",
					      "percentOfField": "TOTAL_HU"
					   },
					   {
					      "fieldName":"RENTER_OCC_HU",
					      "fieldAlias":"RENTER_OCC_HU",
					      "fieldType":"Number",
					      "tableHeader":"Renter-Occupied Housing Units",
					      "category":"Housing",
					      "rowID":34,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"",
					      "percentOfField": "TOTAL_HU"
					   },
					   {
					      "fieldName":"AVG_HH_SIZE",
					      "fieldAlias":"AVG_HH_SIZE",
					      "fieldType":"Number",
					      "tableHeader":"Average Household Size",
					      "category":"Housing",
					      "rowID":35,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":false,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"AVG_HH_SIZE_OWNER_HU",
					      "fieldAlias":"AVG_HH_SIZE_OWNER_HU",
					      "fieldType":"Number",
					      "tableHeader":"Avg Household Size for Owner-Occupied Housing Units",
					      "category":"Housing",
					      "rowID":36,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":false,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"AVG_HH_SIZE_RENTER_HU",
					      "fieldAlias":"AVG_HH_SIZE_RENTER_HU",
					      "fieldType":"Number",
					      "tableHeader":"Avg Household Size for Renter-Occupied Housing Units",
					      "category":"Housing",
					      "rowID":37,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"",
					      "chartType":"",
					      "canSum":false,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   }
					]
		        }
            return censusFieldsConfig;
        }
    );
}());