(function() {

    "use strict";

    define(

        function() {
            var censusFieldsConfig = new function() {
            var self = this;
			self.fields = 
					[
					   {
					      "fieldName":"ACRES",
					      "fieldAlias":"ACRES",
					      "fieldType":"Number",
					      "tableHeader":"Total Acres",
					      "category":"General",
					      "rowID":1,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"General",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"SQMI",
					      "fieldAlias":"SQMI",
					      "fieldType":"Number",
					      "tableHeader":"Total Square Miles",
					      "category":"General",
					      "rowID":2,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"General",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"TOTAL_POP",
					      "fieldAlias":"TOTAL_POP",
					      "fieldType":"Number",
					      "tableHeader":"Total Population",
					      "category":"General",
					      "rowID":3,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"General",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"MEDIAN_AGE",
					      "fieldAlias":"MEDIAN_AGE",
					      "fieldType":"Number",
					      "tableHeader":"Median Age",
					      "category":"Age",
					      "rowID":4,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"UNDER5",
					      "fieldAlias":"UNDER5",
					      "fieldType":"Number",
					      "tableHeader":"Under 5",
					      "category":"Age",
					      "rowID":5,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_UNDER5"
					   },
					   {
					      "fieldName":"AGE5TO17",
					      "fieldAlias":"AGE5TO17",
					      "fieldType":"Number",
					      "tableHeader":"5 to 17",
					      "category":"Age",
					      "rowID":6,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_5TO17"
					   },
					   {
					      "fieldName":"AGE18TO34",
					      "fieldAlias":"AGE18TO34",
					      "fieldType":"Number",
					      "tableHeader":"18 to 34",
					      "category":"Age",
					      "rowID":7,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_18TO34"
					   },
					   {
					      "fieldName":"AGE35TO49",
					      "fieldAlias":"AGE35TO49",
					      "fieldType":"Number",
					      "tableHeader":"35 to 49",
					      "category":"Age",
					      "rowID":8,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_35TO49"
					   },
					   {
					      "fieldName":"AGE50TO64",
					      "fieldAlias":"AGE50TO64",
					      "fieldType":"Number",
					      "tableHeader":"50 to 64",
					      "category":"Age",
					      "rowID":9,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_50TO64"
					   },
					   {
					      "fieldName":"AGE65TO84",
					      "fieldAlias":"AGE65TO84",
					      "fieldType":"Number",
					      "tableHeader":"65 to 84",
					      "category":"Age",
					      "rowID":10,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_65TO84"
					   },
					   {
					      "fieldName":"AGE85PLUS",
					      "fieldAlias":"AGE85PLUS",
					      "fieldType":"Number",
					      "tableHeader":"85 and over",
					      "category":"Age",
					      "rowID":11,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_85PLUS"
					   },
					   {
					      "fieldName":"AGE50PLUS",
					      "fieldAlias":"AGE50PLUS",
					      "fieldType":"Number",
					      "tableHeader":"50 and over",
					      "category":"Age",
					      "rowID":12,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_50PLUS"
					   },
					   {
					      "fieldName":"AGE60PLUS",
					      "fieldAlias":"AGE60PLUS",
					      "fieldType":"Number",
					      "tableHeader":"60 and over",
					      "category":"Age",
					      "rowID":13,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_60PLUS"
					   },
					   {
					      "fieldName":"AGE65PLUS",
					      "fieldAlias":"AGE65PLUS",
					      "fieldType":"Number",
					      "tableHeader":"65 and over",
					      "category":"Age",
					      "rowID":14,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_65PLUS"
					   },
					   {
					      "fieldName":"AGE70PLUS",
					      "fieldAlias":"AGE70PLUS",
					      "fieldType":"Number",
					      "tableHeader":"70 and over",
					      "category":"Age",
					      "rowID":15,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_70PLUS"
					   },
					   {
					      "fieldName":"AGE75PLUS",
					      "fieldAlias":"AGE75PLUS",
					      "fieldType":"Number",
					      "tableHeader":"75 and over",
					      "category":"Age",
					      "rowID":16,
					      "groupID":"<span class='myHiddenClass'>02</span>Age",
					      "chartCategory":"Age",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_AGE_75PLUS"
					   },
					   {
					      "fieldName":"WHITE",
					      "fieldAlias":"WHITE",
					      "fieldType":"Number",
					      "tableHeader":"White",
					      "category":"Population by Race",
					      "rowID":17,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_WHITE"
					   },
					   {
					      "fieldName":"BLACK",
					      "fieldAlias":"BLACK",
					      "fieldType":"Number",
					      "tableHeader":"Black",
					      "category":"Population by Race",
					      "rowID":18,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_BLACK"
					   },
					   {
					      "fieldName":"NATIVE",
					      "fieldAlias":"NATIVE",
					      "fieldType":"Number",
					      "tableHeader":"Native American",
					      "category":"Population by Race",
					      "rowID":19,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_NATIVE"
					   },
					   {
					      "fieldName":"ASIAN",
					      "fieldAlias":"ASIAN",
					      "fieldType":"Number",
					      "tableHeader":"Asian",
					      "category":"Population by Race",
					      "rowID":20,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_ASIAN"
					   },
					   {
					      "fieldName":"PACIFIC",
					      "fieldAlias":"PACIFIC",
					      "fieldType":"Number",
					      "tableHeader":"Pacific Islander",
					      "category":"Population by Race",
					      "rowID":21,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_PACIFIC"
					   },
					   {
					      "fieldName":"OTHER",
					      "fieldAlias":"OTHER",
					      "fieldType":"Number",
					      "tableHeader":"Other Race",
					      "category":"Population by Race",
					      "rowID":22,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_OTHER"
					   },
					   {
					      "fieldName":"TWO_OR_MORE",
					      "fieldAlias":"TWO_OR_MORE",
					      "fieldType":"Number",
					      "tableHeader":"Two or More",
					      "category":"Population by Race",
					      "rowID":23,
					      "groupID":"<span class='myHiddenClass'>03</span>Population by Race",
					      "chartCategory":"Population by Race",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_TWO_OR_MORE"
					   },
					   {
					      "fieldName":"HISPANIC",
					      "fieldAlias":"HISPANIC",
					      "fieldType":"Number",
					      "tableHeader":"Hispanic",
					      "category":"Population by Ethnicity",
					      "rowID":24,
					      "groupID":"<span class='myHiddenClass'>04</span>Population by Ethnicity",
					      "chartCategory":"Population by Ethnicity",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_HISPANIC"
					   },
					   {
					      "fieldName":"NOT_HISPANIC",
					      "fieldAlias":"NOT_HISPANIC",
					      "fieldType":"Number",
					      "tableHeader":"Non-Hispanic",
					      "category":"Population by Ethnicity",
					      "rowID":25,
					      "groupID":"<span class='myHiddenClass'>04</span>Population by Ethnicity",
					      "chartCategory":"Population by Ethnicity",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_NOT_HISPANIC"
					   },
					   {
					      "fieldName":"MINORITY_POP",
					      "fieldAlias":"MINORITY_POP",
					      "fieldType":"Number",
					      "tableHeader":"Minority Population",
					      "category":"General",
					      "rowID":26,
					      "groupID":"<span class='myHiddenClass'>01</span>General",
					      "chartCategory":"General",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_MINORITY_POP"
					   },
					   {
					      "fieldName":"TOTAL_HU",
					      "fieldAlias":"TOTAL_HU",
					      "fieldType":"Number",
					      "tableHeader":"Housing Units",
					      "category":"Housing",
					      "rowID":27,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"VACANCY_RATE"
					   },
					   {
					      "fieldName":"OCCUPIED_HU",
					      "fieldAlias":"OCCUPIED_HU",
					      "fieldType":"Number",
					      "tableHeader":"Occupied Units",
					      "category":"Housing",
					      "rowID":28,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_SEASONAL_HU"
					   },
					   {
					      "fieldName":"VACANT_HU",
					      "fieldAlias":"VACANT_HU",
					      "fieldType":"Number",
					      "tableHeader":"Vacant Units",
					      "category":"Housing",
					      "rowID":29,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"pie",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"NON_SEASONAL_VACANCY_RATE"
					   },
					   {
					      "fieldName":"SEASONAL_HU",
					      "fieldAlias":"SEASONAL_HU",
					      "fieldType":"Number",
					      "tableHeader":"Seasonal Housing",
					      "category":"Housing",
					      "rowID":30,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"NON_SEASONAL_HU",
					      "fieldAlias":"NON_SEASONAL_HU",
					      "fieldType":"Number",
					      "tableHeader":"Non-Seasonal Units",
					      "category":"Housing",
					      "rowID":31,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"NON_SEASONAL_VAC_HU",
					      "fieldAlias":"NON_SEASONAL_VAC_HU",
					      "fieldType":"Number",
					      "tableHeader":"Non-Seasonal Vacation Units",
					      "category":"Housing",
					      "rowID":32,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_OWNER_OCCUPIED_HU"
					   },
					   {
					      "fieldName":"OWNER_OCC_HU",
					      "fieldAlias":"OWNER_OCC_HU",
					      "fieldType":"Number",
					      "tableHeader":"Occupied Owner Units",
					      "category":"Housing",
					      "rowID":33,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":"PCT_RENTER_OCCUPIED_HU"
					   },
					   {
					      "fieldName":"RENTER_OCC_HU",
					      "fieldAlias":"RENTER_OCC_HU",
					      "fieldType":"Number",
					      "tableHeader":"Renter Occupied Units",
					      "category":"Housing",
					      "rowID":34,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"AVG_HH_SIZE",
					      "fieldAlias":"AVG_HH_SIZE",
					      "fieldType":"Number",
					      "tableHeader":"Average Household Size",
					      "category":"Housing",
					      "rowID":35,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"AVG_HH_SIZE_OWNER_HU",
					      "fieldAlias":"AVG_HH_SIZE_OWNER_HU",
					      "fieldType":"Number",
					      "tableHeader":"Average Household Size for Owner Housing Units",
					      "category":"Housing",
					      "rowID":36,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"AVG_HH_SIZE_RENTER_HU",
					      "fieldAlias":"AVG_HH_SIZE_RENTER_HU",
					      "fieldType":"Number",
					      "tableHeader":"Average Household Size for Renter Housing Units",
					      "category":"Housing",
					      "rowID":37,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"POP_PER_SQMI",
					      "fieldAlias":"POP_PER_SQMI",
					      "fieldType":"Percent",
					      "tableHeader":"Population Per Square Mile",
					      "category":"Housing",
					      "rowID":65,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   },
					   {
					      "fieldName":"HU_PER_SQMI",
					      "fieldAlias":"HU_PER_SQMI",
					      "fieldType":"Percent",
					      "tableHeader":"Housing Units Per Square Mile",
					      "category":"Housing",
					      "rowID":66,
					      "groupID":"<span class='myHiddenClass'>05</span>Housing",
					      "chartCategory":"Housing",
					      "chartType":"",
					      "canSum":true,
					      "dataSource":"Census 2010",
					      "class":null,
					      "timePeriod":null,
					      "percentField":""
					   }
					]
		        }
            return censusFieldsConfig;
        }
    );
}());