app.acsFieldsConfig = [
    {
        fieldName: "total_pop",
        fieldAlias: "Total Population",
        fieldType: "Number",
        tableHeader: "Total Population ",
        category: "Gender and Age",
        indentLevel: 0,
        universeField: 1,
        rowID: 3,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "gender",
        fieldAlias: "Gender",
        fieldType: "Number",
        tableHeader: "Gender",
        category: "Gender and Age",
        indentLevel: 0,
        universeField: 2,
        rowID: 4,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "male",
        fieldAlias: "Male",
        fieldType: "Number",
        tableHeader: "Male",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 5,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "female",
        fieldAlias: "Female",
        fieldType: "Number",
        tableHeader: "Female",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 6,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age",
        fieldAlias: "Age",
        fieldType: "Number",
        tableHeader: "Age",
        category: "Gender and Age",
        indentLevel: 0,
        universeField: 2,
        rowID: 7,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "median_age",
        fieldAlias: "Median Age",
        fieldType: "Number",
        tableHeader: "Median Age",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 8,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "under5",
        fieldAlias: "Under 5 years",
        fieldType: "Number",
        tableHeader: "Under 5 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 9,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age5to9",
        fieldAlias: "5 to 9 years",
        fieldType: "Number",
        tableHeader: "5 to 9 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 10,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age10to14",
        fieldAlias: "10 to 14 years",
        fieldType: "Number",
        tableHeader: "10 to 14 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 11,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age15to19",
        fieldAlias: "15 to 19 years",
        fieldType: "Number",
        tableHeader: "15 to 19 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 12,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age20to24",
        fieldAlias: "20 to 24 years",
        fieldType: "Number",
        tableHeader: "20 to 24 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 13,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age25to34",
        fieldAlias: "25 to 34 years",
        fieldType: "Number",
        tableHeader: "25 to 34 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 14,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age35to44",
        fieldAlias: "35 to 44 years",
        fieldType: "Number",
        tableHeader: "35 to 44 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 15,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age45to54",
        fieldAlias: "45 to 54 years",
        fieldType: "Number",
        tableHeader: "45 to 54 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 16,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age55to59",
        fieldAlias: "55 to 59 years",
        fieldType: "Number",
        tableHeader: "55 to 59 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 17,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age60to64",
        fieldAlias: "60 to 64 years",
        fieldType: "Number",
        tableHeader: "60 to 64 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 18,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age65to74",
        fieldAlias: "65 to 74 years",
        fieldType: "Number",
        tableHeader: "65 to 74 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 19,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age75to84",
        fieldAlias: "75 to 84 years",
        fieldType: "Number",
        tableHeader: "75 to 84 years",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 20,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age85plus",
        fieldAlias: "85 years and over",
        fieldType: "Number",
        tableHeader: "85 years and over",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 21,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "Age",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "select age groups",
        fieldAlias: "Select Age Groups",
        fieldType: "Number",
        tableHeader: "Select Age Groups",
        category: "Gender and Age",
        indentLevel: 0,
        universeField: 2,
        rowID: 22,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "age18plus",
        fieldAlias: "18 years and over",
        fieldType: "Number",
        tableHeader: "18 years and over",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 23,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age21plus",
        fieldAlias: "21 years and over",
        fieldType: "Number",
        tableHeader: "21 years and over",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 24,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age62plus",
        fieldAlias: "62 years and over",
        fieldType: "Number",
        tableHeader: "62 years and over",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 25,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age65plus",
        fieldAlias: "65 years and over",
        fieldType: "Number",
        tableHeader: "65 years and over",
        category: "Gender and Age",
        indentLevel: 1,
        universeField: 0,
        rowID: 26,
        groupID: "<span class='myHiddenClass'>02</span>Gender and Age",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "total_pop",
        fieldAlias: "Total Population",
        fieldType: "Number",
        tableHeader: "Total Population",
        category: "Race and Ethnicity",
        indentLevel: 0,
        universeField: 1,
        rowID: 27,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "hispanic",
        fieldAlias: "Hispanic",
        fieldType: "Number",
        tableHeader: "Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 1,
        universeField: 0,
        rowID: 28,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "non-hispanic",
        fieldAlias: "Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 1,
        universeField: 2,
        rowID: 29,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "white_non_hispanic",
        fieldAlias: "White, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "White, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 30,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "black_non_hispanic",
        fieldAlias: "Black, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Black, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 31,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "native_non_hispanic",
        fieldAlias: "Native American, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Native American, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 32,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "asian_non_hispanic",
        fieldAlias: "Asian, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Asian, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 33,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "pacific_non_hispanic",
        fieldAlias: "Pacific Islander, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Pacific Islander, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 34,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "other_non_hispanic",
        fieldAlias: "Other, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Other, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 35,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "two_or_more_non_hispanic",
        fieldAlias: "Two or More, Non-Hispanic",
        fieldType: "Number",
        tableHeader: "Two or More, Non-Hispanic",
        category: "Race and Ethnicity",
        indentLevel: 2,
        universeField: 0,
        rowID: 36,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "Race and Ethnicity",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "minority_pop",
        fieldAlias: "Minority",
        fieldType: "Number",
        tableHeader:
            'Minority<i id="minorityTooltip" style="margin-left:6px;" class="fas fa-question-circle" data-toggle="tooltip" data-placement="top" title="Minority is defined as Total Population less White, Non-Hispanic Population"></i>',
        category: "Race and Ethnicity",
        indentLevel: 1,
        universeField: 0,
        rowID: 37,
        groupID: "<span class='myHiddenClass'>03</span>Race and Ethnicity",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_pop",
    },
    {
        fieldName: "age25plus",
        fieldAlias: "Population 25 years and over",
        fieldType: "Number",
        tableHeader: "Population 25 years and over",
        category: "Educational Attainment",
        indentLevel: 0,
        universeField: 1,
        rowID: 38,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "lt9grade",
        fieldAlias: "Less than 9th Grade",
        fieldType: "Number",
        tableHeader: "Less than 9th Grade",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 39,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "nohsdiploma",
        fieldAlias: "9th to 12th Grade, No Diploma",
        fieldType: "Number",
        tableHeader: "9th to 12th Grade, No Diploma",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 40,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "hsgrad",
        fieldAlias: "High School Graduate (includes equivalency)",
        fieldType: "Number",
        tableHeader: "High School Graduate (includes equivalency)",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 41,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "somecollege",
        fieldAlias: "Some College, No Degree",
        fieldType: "Number",
        tableHeader: "Some College, No Degree",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 42,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "associates",
        fieldAlias: "Associate Degree",
        fieldType: "Number",
        tableHeader: "Associate Degree",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 43,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "bachelors",
        fieldAlias: "Bachelor's Degree",
        fieldType: "Number",
        tableHeader: "Bachelor's Degree",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 44,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "gradprof",
        fieldAlias: "Graduate or Professional Degree",
        fieldType: "Number",
        tableHeader: "Graduate or Professional Degree",
        category: "Educational Attainment",
        indentLevel: 1,
        universeField: 0,
        rowID: 45,
        groupID: "<span class='myHiddenClass'>04</span>Educational Attainment",
        chartCategory: "Educational Attainment",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "age25plus",
    },
    {
        fieldName: "age5plus",
        fieldAlias: "Population 5 years and over",
        fieldType: "Number",
        tableHeader: "Population 5 years and over",
        category: "Ability to Speak English",
        indentLevel: 0,
        universeField: 1,
        rowID: 46,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "speak_only_eng",
        fieldAlias: "Speak Only English",
        fieldType: "Number",
        tableHeader: "Speak Only English",
        category: "Ability to Speak English",
        indentLevel: 1,
        universeField: 0,
        rowID: 47,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "age5plus",
    },
    {
        fieldName: "speak_other_langs",
        fieldAlias: "Speak Other Languages",
        fieldType: "Number",
        tableHeader: "Speak Other Languages",
        category: "Ability to Speak English",
        indentLevel: 1,
        universeField: 0,
        rowID: 48,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "age5plus",
    },
    {
        fieldName: "speak_eng_verywell",
        fieldAlias: "Speak English ''very well''",
        fieldType: "Number",
        tableHeader: "Speak English ''very well''",
        category: "Ability to Speak English",
        indentLevel: 2,
        universeField: 0,
        rowID: 49,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "limited_eng_prof",
        fieldAlias: "Persons with Limited English Proficiency (LEP)",
        fieldType: "Number",
        tableHeader: "Persons with Limited English Proficiency (LEP)",
        category: "Ability to Speak English",
        indentLevel: 2,
        universeField: 0,
        rowID: 50,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "speak_eng_well",
        fieldAlias: "Speak English ''well''",
        fieldType: "Number",
        tableHeader: "Speak English ''well''",
        category: "Ability to Speak English",
        indentLevel: 3,
        universeField: 0,
        rowID: 51,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "speak_eng_notwell",
        fieldAlias: "Speak English ''not well''",
        fieldType: "Number",
        tableHeader: "Speak English ''not well''",
        category: "Ability to Speak English",
        indentLevel: 3,
        universeField: 0,
        rowID: 52,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "speak_eng_notatall",
        fieldAlias: "Speak English ''not at all''",
        fieldType: "Number",
        tableHeader: "Speak English ''not at all''",
        category: "Ability to Speak English",
        indentLevel: 3,
        universeField: 0,
        rowID: 53,
        groupID:
            "<span class='myHiddenClass'>05</span>Ability to Speak English",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "civ_pop_18plus",
        fieldAlias: "Civilian Population 18 years and over",
        fieldType: "Number",
        tableHeader: "Civilian Population 18 years and over",
        category: "Veterans Status",
        indentLevel: 0,
        universeField: 1,
        rowID: 54,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "veterans",
        fieldAlias: "Civilian veterans",
        fieldType: "Number",
        tableHeader: "Civilian veterans",
        category: "Veterans Status",
        indentLevel: 1,
        universeField: 0,
        rowID: 55,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "civ_pop_18plus",
    },
    {
        fieldName: "veterans by gender",
        fieldAlias: "Veterans by Gender",
        fieldType: "Number",
        tableHeader: "Veterans by Gender",
        category: "Veterans Status",
        indentLevel: 1,
        universeField: 2,
        rowID: 56,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "veterans",
    },
    {
        fieldName: "male_veterans",
        fieldAlias: "Male",
        fieldType: "Number",
        tableHeader: "Male",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 57,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "female_veterans",
        fieldAlias: "Female",
        fieldType: "Number",
        tableHeader: "Female",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 58,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "veterans by age",
        fieldAlias: "Veterans by Age",
        fieldType: "Number",
        tableHeader: "Veterans by Age",
        category: "Veterans Status",
        indentLevel: 1,
        universeField: 2,
        rowID: 59,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "vets_18to34",
        fieldAlias: "18 to 34 years",
        fieldType: "Number",
        tableHeader: "18 to 34 years",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 60,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "vets_35to54",
        fieldAlias: "35 to 54 years",
        fieldType: "Number",
        tableHeader: "35 to 54 years",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 61,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "vets_55to64",
        fieldAlias: "55 to 64 years",
        fieldType: "Number",
        tableHeader: "55 to 64 years",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 62,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "vets_65to74",
        fieldAlias: "65 to 74 years ",
        fieldType: "Number",
        tableHeader: "65 to 74 years ",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 63,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "vets_75plus",
        fieldAlias: "75 years and over",
        fieldType: "Number",
        tableHeader: "75 years and over",
        category: "Veterans Status",
        indentLevel: 2,
        universeField: 0,
        rowID: 64,
        groupID: "<span class='myHiddenClass'>06</span>Veterans Status",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "total_households",
        fieldAlias: "Total Households",
        fieldType: "Number",
        tableHeader: "Total Households",
        category: "Households",
        indentLevel: 0,
        universeField: 1,
        rowID: 65,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "avg_hh_size",
        fieldAlias: "Average Household Size",
        fieldType: "Number",
        tableHeader: "Average Household Size",
        category: "Households",
        indentLevel: 1,
        universeField: 0,
        rowID: 66,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "family_households",
        fieldAlias: "Family Households (Families)",
        fieldType: "Number",
        tableHeader: "Family Households (Families)",
        category: "Households",
        indentLevel: 1,
        universeField: 0,
        rowID: 67,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_households",
    },
    {
        fieldName: "married_couple_family",
        fieldAlias: "Married-couple family",
        fieldType: "Number",
        tableHeader: "Married-couple family",
        category: "Households",
        indentLevel: 2,
        universeField: 0,
        rowID: 68,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "female_householder_nohusb",
        fieldAlias: "Female Householder, no husband present",
        fieldType: "Number",
        tableHeader: "Female Householder, no husband present",
        category: "Households",
        indentLevel: 2,
        universeField: 0,
        rowID: 69,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "female_hh_child_under18",
        fieldAlias: "with own children under 18 years",
        fieldType: "Number",
        tableHeader: "with own children under 18 years",
        category: "Households",
        indentLevel: 3,
        universeField: 0,
        rowID: 70,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "non_family_households",
        fieldAlias: "Nonfamily Households",
        fieldType: "Number",
        tableHeader: "Nonfamily Households",
        category: "Households",
        indentLevel: 1,
        universeField: 0,
        rowID: 71,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_households",
    },
    {
        fieldName: "nonfam_hh_live_alone",
        fieldAlias: "Householder living alone",
        fieldType: "Number",
        tableHeader: "Householder living alone",
        category: "Households",
        indentLevel: 2,
        universeField: 0,
        rowID: 72,
        groupID: "<span class='myHiddenClass'>07</span>Households",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "total_hh_for_income",
        fieldAlias: "Total Households",
        fieldType: "Number",
        tableHeader: "Total Households",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 0,
        universeField: 1,
        rowID: 73,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "median_household_income",
        fieldAlias: "Median Household Income (dollars)",
        fieldType: "Currency",
        tableHeader: "Median Household Income (dollars)",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 74,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "hh_less_than_10k",
        fieldAlias: "Less than $10,000",
        fieldType: "Number",
        tableHeader: "Less than $10,000",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 75,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_10k_to_14k",
        fieldAlias: "$10,000 to $14,999",
        fieldType: "Number",
        tableHeader: "$10,000 to $14,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 76,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_15k_to_24k",
        fieldAlias: "$15,000 to $24,999",
        fieldType: "Number",
        tableHeader: "$15,000 to $24,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 77,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_25k_to_34k",
        fieldAlias: "$25,000 to $34,999",
        fieldType: "Number",
        tableHeader: "$25,000 to $34,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 78,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_35k_to_49k",
        fieldAlias: "$35,000 to 49,999",
        fieldType: "Number",
        tableHeader: "$35,000 to 49,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 79,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_50k_to_74k",
        fieldAlias: "$50,000 to $74,999",
        fieldType: "Number",
        tableHeader: "$50,000 to $74,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 80,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_75k_to_99k",
        fieldAlias: "$75,000 to $99,999",
        fieldType: "Number",
        tableHeader: "$75,000 to $99,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 81,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_100k_to_149k",
        fieldAlias: "$100,000 to $149,999",
        fieldType: "Number",
        tableHeader: "$100,000 to $149,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 82,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_150k_to_199k",
        fieldAlias: "$150,000 to $199,999",
        fieldType: "Number",
        tableHeader: "$150,000 to $199,999",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 83,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "hh_200k_plus",
        fieldAlias: "$200,000 or more",
        fieldType: "Number",
        tableHeader: "$200,000 or more",
        category: "Household Income (in 2019 inflation-adjusted dollars)",
        indentLevel: 1,
        universeField: 0,
        rowID: 84,
        groupID:
            "<span class='myHiddenClass'>08</span>Household Income (in 2019 inflation-adjusted dollars)",
        chartCategory: "Household Income",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "total_hh_for_income",
    },
    {
        fieldName: "pop_for_poverty",
        fieldAlias: "Persons for whom poverty status is determined",
        fieldType: "Number",
        tableHeader: "Persons for whom poverty status is determined",
        category: "Poverty Status in the Past 12 Months",
        indentLevel: 0,
        universeField: 1,
        rowID: 85,
        groupID:
            "<span class='myHiddenClass'>09</span>Poverty Status in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "income_below_poverty",
        fieldAlias: "Persons with income below poverty level",
        fieldType: "Number",
        tableHeader: "Persons with income below poverty level",
        category: "Poverty Status in the Past 12 Months",
        indentLevel: 1,
        universeField: 0,
        rowID: 86,
        groupID:
            "<span class='myHiddenClass'>09</span>Poverty Status in the Past 12 Months",
        chartCategory: "Poverty",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "pop_for_poverty",
    },
    {
        fieldName: "income_below_150pct_poverty",
        fieldAlias: "Persons with income below 150% of poverty level",
        fieldType: "Number",
        tableHeader: "Persons with income below 150% of poverty level",
        category: "Poverty Status in the Past 12 Months",
        indentLevel: 1,
        universeField: 0,
        rowID: 87,
        groupID:
            "<span class='myHiddenClass'>09</span>Poverty Status in the Past 12 Months",
        chartCategory: "Poverty",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "pop_for_poverty",
    },
    {
        fieldName: "income_below_200pct_poverty",
        fieldAlias: "Persons with income below 200% of poverty level",
        fieldType: "Number",
        tableHeader: "Persons with income below 200% of poverty level",
        category: "Poverty Status in the Past 12 Months",
        indentLevel: 1,
        universeField: 0,
        rowID: 88,
        groupID:
            "<span class='myHiddenClass'>09</span>Poverty Status in the Past 12 Months",
        chartCategory: "Poverty",
        chartType: "bar",
        canSum: true,
        parentField: "",
        percentOfField: "pop_for_poverty",
    },
    {
        fieldName: "total_families",
        fieldAlias: "Total Families",
        fieldType: "Number",
        tableHeader: "Total Families",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 0,
        universeField: 1,
        rowID: 89,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "fam_income_below_poverty",
        fieldAlias: "Families with income below poverty level",
        fieldType: "Number",
        tableHeader: "Families with income below poverty level",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 1,
        universeField: 0,
        rowID: 90,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_families",
    },
    {
        fieldName: "marriedcouple_belowpov",
        fieldAlias: "Married-couple family",
        fieldType: "Number",
        tableHeader: "Married-couple family",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 2,
        universeField: 0,
        rowID: 91,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "couple_blwpov_childunder18",
        fieldAlias: "with related children under 18 years ",
        fieldType: "Number",
        tableHeader: "with related children under 18 years ",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 3,
        universeField: 0,
        rowID: 92,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "female_blwpov_nohusb",
        fieldAlias: "Female householder, no husband present",
        fieldType: "Number",
        tableHeader: "Female householder, no husband present",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 2,
        universeField: 0,
        rowID: 93,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "female_blwpov_childunder18",
        fieldAlias: "with related children under 18 years",
        fieldType: "Number",
        tableHeader: "with related children under 18 years",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 3,
        universeField: 0,
        rowID: 94,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "male_blwpov_nowife",
        fieldAlias: "Male householder, no wife present",
        fieldType: "Number",
        tableHeader: "Male householder, no wife present",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 2,
        universeField: 0,
        rowID: 95,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "male_blwpov_childunder18",
        fieldAlias: "with related children under 18 years   ",
        fieldType: "Number",
        tableHeader: "with related children under 18 years   ",
        category: "Poverty Status for Families in the Past 12 Months",
        indentLevel: 3,
        universeField: 0,
        rowID: 96,
        groupID:
            "<span class='myHiddenClass'>10</span>Poverty Status for Families in the Past 12 Months",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "tot_workers_16plus",
        fieldAlias: "Workers 16 years and over",
        fieldType: "Number",
        tableHeader: "Workers 16 years and over",
        category: "Commuting to Work",
        indentLevel: 0,
        universeField: 1,
        rowID: 97,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "drove_alone",
        fieldAlias: "Car or Truck - drive alone",
        fieldType: "Number",
        tableHeader: "Car or Truck - drive alone",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 98,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "carpooled",
        fieldAlias: "Car or Truck - carpool",
        fieldType: "Number",
        tableHeader: "Car or Truck - carpool",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 99,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "public_transportation",
        fieldAlias: "Public Transportation",
        fieldType: "Number",
        tableHeader: "Public Transportation",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 100,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "bicycle",
        fieldAlias: "Bicycle",
        fieldType: "Number",
        tableHeader: "Bicycle",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 101,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "walked",
        fieldAlias: "Walked",
        fieldType: "Number",
        tableHeader: "Walked",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 102,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "taxi_motorcycle_or_other",
        fieldAlias: "Other means (taxicab, motorcycle, etc.)",
        fieldType: "Number",
        tableHeader: "Other means (taxicab, motorcycle, etc.)",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 103,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "worked_from_home",
        fieldAlias: "Work at home",
        fieldType: "Number",
        tableHeader: "Work at home",
        category: "Commuting to Work",
        indentLevel: 1,
        universeField: 0,
        rowID: 104,
        groupID: "<span class='myHiddenClass'>11</span>Commuting to Work",
        chartCategory: "Commute",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "tot_workers_16plus",
    },
    {
        fieldName: "civilian_employed_16_plus",
        fieldAlias: "Civilian employed population 16 years and over",
        fieldType: "Number",
        tableHeader: "Civilian employed population 16 years and over",
        category: "Occupation",
        indentLevel: 0,
        universeField: 1,
        rowID: 105,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "mgbizsciart",
        fieldAlias: "Management, business, science, and arts occupations",
        fieldType: "Number",
        tableHeader: "Management, business, science, and arts occupations",
        category: "Occupation",
        indentLevel: 1,
        universeField: 0,
        rowID: 106,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "Occupation",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "civilian_employed_16_plus",
    },
    {
        fieldName: "mgbizfin",
        fieldAlias: "Management, business, and financial occupations",
        fieldType: "Number",
        tableHeader: "Management, business, and financial occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 107,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "MGBIZSCIART",
        percentOfField: "",
    },
    {
        fieldName: "mgmt",
        fieldAlias: "Management occupations",
        fieldType: "Number",
        tableHeader: "Management occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 108,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "MGBIZFIN",
        percentOfField: "",
    },
    {
        fieldName: "bizfin",
        fieldAlias: "Business and financial operations occupations",
        fieldType: "Number",
        tableHeader: "Business and financial operations occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 109,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "MGBIZFIN",
        percentOfField: "",
    },
    {
        fieldName: "compengsci",
        fieldAlias: "Computer, engineering, and science occupations",
        fieldType: "Number",
        tableHeader: "Computer, engineering, and science occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 110,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "compmath",
        fieldAlias: "Computer and mathematical occupations",
        fieldType: "Number",
        tableHeader: "Computer and mathematical occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 111,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "COMPENGSCI",
        percentOfField: "",
    },
    {
        fieldName: "archengin",
        fieldAlias: "Architecture and engineering occupations",
        fieldType: "Number",
        tableHeader: "Architecture and engineering occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 112,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "COMPENGSCI",
        percentOfField: "",
    },
    {
        fieldName: "lifephyssocsci",
        fieldAlias: "Life, physical, and social science occupations",
        fieldType: "Number",
        tableHeader: "Life, physical, and social science occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 113,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "edulegcomartmedia",
        fieldAlias:
            "Education, legal, community service, arts, and media occupations",
        fieldType: "Number",
        tableHeader:
            "Education, legal, community service, arts, and media occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 114,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "commsocserv",
        fieldAlias: "Community and social service occupations",
        fieldType: "Number",
        tableHeader: "Community and social service occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 115,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "EDULEGCOMARTMEDIA",
        percentOfField: "",
    },
    {
        fieldName: "legal",
        fieldAlias: "Legal occupations",
        fieldType: "Number",
        tableHeader: "Legal occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 116,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "EDULEGCOMARTMEDIA",
        percentOfField: "",
    },
    {
        fieldName: "edutrainlib",
        fieldAlias: "Education, training, and library occupations",
        fieldType: "Number",
        tableHeader: "Education, training, and library occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 117,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "EDULEGCOMARTMEDIA",
        percentOfField: "",
    },
    {
        fieldName: "artentsportmedia",
        fieldAlias:
            "Arts, design, entertainment, sports, and media occupations",
        fieldType: "Number",
        tableHeader:
            "Arts, design, entertainment, sports, and media occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 118,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "EDULEGCOMARTMEDIA",
        percentOfField: "",
    },
    {
        fieldName: "healthtechnical",
        fieldAlias: "Healthcare practitioners and technical occupations",
        fieldType: "Number",
        tableHeader: "Healthcare practitioners and technical occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 119,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "healthdiagtechocc",
        fieldAlias:
            "Health diagnosing and treating practitioners and other technical occupations",
        fieldType: "Number",
        tableHeader:
            "Health diagnosing and treating practitioners and other technical occupations",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 120,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "HEALTHTECHNICAL",
        percentOfField: "",
    },
    {
        fieldName: "healthtech",
        fieldAlias: "Health technologists and technicians ",
        fieldType: "Number",
        tableHeader: "Health technologists and technicians ",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 121,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "HEALTHTECHNICAL",
        percentOfField: "",
    },
    {
        fieldName: "serviceocc",
        fieldAlias: "Service occupations",
        fieldType: "Number",
        tableHeader: "Service occupations",
        category: "Occupation",
        indentLevel: 1,
        universeField: 0,
        rowID: 122,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "Occupation",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "civilian_employed_16_plus",
    },
    {
        fieldName: "healthsupport",
        fieldAlias: "Healthcare support occupations",
        fieldType: "Number",
        tableHeader: "Healthcare support occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 123,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SERVICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "protectiveserv",
        fieldAlias: "Protective service occupations",
        fieldType: "Number",
        tableHeader: "Protective service occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 124,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SERVICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "firefighting",
        fieldAlias:
            "Firefighting and prevention, and other protective service workers including supervisors",
        fieldType: "Number",
        tableHeader:
            "Firefighting and prevention, and other protective service workers including supervisors",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 125,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "PROTECTIVESERV",
        percentOfField: "",
    },
    {
        fieldName: "lawenforcement",
        fieldAlias: "Law enforcement workers including supervisors",
        fieldType: "Number",
        tableHeader: "Law enforcement workers including supervisors",
        category: "Occupation",
        indentLevel: 3,
        universeField: 0,
        rowID: 126,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "PROTECTIVESERV",
        percentOfField: "",
    },
    {
        fieldName: "foodprep",
        fieldAlias: "Food preparation and serving related occupations",
        fieldType: "Number",
        tableHeader: "Food preparation and serving related occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 127,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SERVICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "groundsmaint",
        fieldAlias: "Building and grounds cleaning and maintenance occupations",
        fieldType: "Number",
        tableHeader:
            "Building and grounds cleaning and maintenance occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 128,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SERVICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "personalcare",
        fieldAlias: "Personal care and service occupations",
        fieldType: "Number",
        tableHeader: "Personal care and service occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 129,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SERVICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "salesofficeocc",
        fieldAlias: "Sales and office occupations",
        fieldType: "Number",
        tableHeader: "Sales and office occupations",
        category: "Occupation",
        indentLevel: 1,
        universeField: 0,
        rowID: 130,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "Occupation",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "civilian_employed_16_plus",
    },
    {
        fieldName: "salesocc",
        fieldAlias: "Sales and related occupations",
        fieldType: "Number",
        tableHeader: "Sales and related occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 131,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SALESOFFICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "officeadmin",
        fieldAlias: "Office and administrative support occupations",
        fieldType: "Number",
        tableHeader: "Office and administrative support occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 132,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "SALESOFFICEOCC",
        percentOfField: "",
    },
    {
        fieldName: "natresources",
        fieldAlias:
            "Natural resources, construction, and maintenance occupations",
        fieldType: "Number",
        tableHeader:
            "Natural resources, construction, and maintenance occupations",
        category: "Occupation",
        indentLevel: 1,
        universeField: 0,
        rowID: 133,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "Occupation",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "civilian_employed_16_plus",
    },
    {
        fieldName: "farmfish",
        fieldAlias: "Farming, fishing, and forestry occupations",
        fieldType: "Number",
        tableHeader: "Farming, fishing, and forestry occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 134,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "NATRESOURCES",
        percentOfField: "",
    },
    {
        fieldName: "construction",
        fieldAlias: "Construction and extraction occupations",
        fieldType: "Number",
        tableHeader: "Construction and extraction occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 135,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "NATRESOURCES",
        percentOfField: "",
    },
    {
        fieldName: "instrepair",
        fieldAlias: "Installation, maintenance, and repair occupations",
        fieldType: "Number",
        tableHeader: "Installation, maintenance, and repair occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 136,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "NATRESOURCES",
        percentOfField: "",
    },
    {
        fieldName: "prodtransmaterial",
        fieldAlias:
            "Production, transportation, and material moving occupations",
        fieldType: "Number",
        tableHeader:
            "Production, transportation, and material moving occupations",
        category: "Occupation",
        indentLevel: 1,
        universeField: 0,
        rowID: 137,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "Occupation",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "civilian_employed_16_plus",
    },
    {
        fieldName: "production",
        fieldAlias: "Production occupations",
        fieldType: "Number",
        tableHeader: "Production occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 138,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "PRODTRANSMATERIAL",
        percentOfField: "",
    },
    {
        fieldName: "transportation",
        fieldAlias: "Transportation occupations",
        fieldType: "Number",
        tableHeader: "Transportation occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 139,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "PRODTRANSMATERIAL",
        percentOfField: "",
    },
    {
        fieldName: "materialmoving",
        fieldAlias: "Material moving occupations",
        fieldType: "Number",
        tableHeader: "Material moving occupations",
        category: "Occupation",
        indentLevel: 2,
        universeField: 0,
        rowID: 140,
        groupID: "<span class='myHiddenClass'>12</span>Occupation",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "PRODTRANSMATERIAL",
        percentOfField: "",
    },
    {
        fieldName: "total_housing_units",
        fieldAlias: "Total Housing Units",
        fieldType: "Number",
        tableHeader: "Total Housing Units",
        category: "Housing",
        indentLevel: 0,
        universeField: 1,
        rowID: 141,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "units",
        fieldAlias: "Occupancy and Tenure",
        fieldType: "Number",
        tableHeader: "Occupancy and Tenure",
        category: "Housing",
        indentLevel: 0,
        universeField: 2,
        rowID: 142,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "occupied_hu",
        fieldAlias: "Occupied Housing Units",
        fieldType: "Number",
        tableHeader: "Occupied Housing Units",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 143,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "Occupancy",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "avg_household_size",
        fieldAlias: "Average Household Size",
        fieldType: "Number",
        tableHeader: "Average Household Size",
        category: "Housing",
        indentLevel: 2,
        universeField: 0,
        rowID: 144,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "owner_occ_hu",
        fieldAlias: "Owner Occupied Housing Units",
        fieldType: "Number",
        tableHeader: "Owner Occupied Housing Units",
        category: "Housing",
        indentLevel: 2,
        universeField: 0,
        rowID: 145,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "Housing Tenure",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "occupied_hu",
    },
    {
        fieldName: "avg_hh_size_owner_hu",
        fieldAlias: "Average Household size of Owner Occupied Housing Units",
        fieldType: "Number",
        tableHeader: "Average Household size of Owner Occupied Housing Units",
        category: "Housing",
        indentLevel: 3,
        universeField: 0,
        rowID: 146,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "median_value",
        fieldAlias: "Median Value (dollars)",
        fieldType: "Currency",
        tableHeader: "Median Value (dollars)",
        category: "Housing",
        indentLevel: 3,
        universeField: 0,
        rowID: 147,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: null,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "renter_occ_hu",
        fieldAlias: "Renter Occupied Housing Units",
        fieldType: "Number",
        tableHeader: "Renter Occupied Housing Units",
        category: "Housing",
        indentLevel: 2,
        universeField: 0,
        rowID: 148,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "Housing Tenure",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "occupied_hu",
    },
    {
        fieldName: "avg_hh_size_renter_hu",
        fieldAlias: "Average Household size of Renter Occupied Housing Units",
        fieldType: "Number",
        tableHeader: "Average Household size of Renter Occupied Housing Units",
        category: "Housing",
        indentLevel: 3,
        universeField: 0,
        rowID: 149,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: false,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "median_gross_rent",
        fieldAlias: "Median Rent (dollars)",
        fieldType: "Currency",
        tableHeader: "Median Rent (dollars)",
        category: "Housing",
        indentLevel: 3,
        universeField: 0,
        rowID: 150,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: false,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "vacant_hu",
        fieldAlias: "Vacant Housing Units",
        fieldType: "Number",
        tableHeader: "Vacant Housing Units",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 151,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "Occupancy",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "seasonal_vacant",
        fieldAlias: "For seasonal, recreational, or occasional use",
        fieldType: "Number",
        tableHeader: "For seasonal, recreational, or occasional use",
        category: "Housing",
        indentLevel: 2,
        universeField: 0,
        rowID: 152,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "all_other_vacant",
        fieldAlias: "All other vacant",
        fieldType: "Number",
        tableHeader: "All other vacant",
        category: "Housing",
        indentLevel: 2,
        universeField: 0,
        rowID: 153,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "units",
        fieldAlias: "Units in Structure",
        fieldType: "Number",
        tableHeader: "Units in Structure",
        category: "Housing",
        indentLevel: 0,
        universeField: 2,
        rowID: 154,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "one_unit_detached",
        fieldAlias: "1, detached",
        fieldType: "Number",
        tableHeader: "1, detached",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 155,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "one_unit_attached",
        fieldAlias: "1, attached",
        fieldType: "Number",
        tableHeader: "1, attached",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 156,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "two_to_nine_units",
        fieldAlias: "2 to 9",
        fieldType: "Number",
        tableHeader: "2 to 9",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 157,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "ten_or_more_units",
        fieldAlias: "10 or more",
        fieldType: "Number",
        tableHeader: "10 or more",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 158,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "mobile_home",
        fieldAlias: "Mobile Home",
        fieldType: "Number",
        tableHeader: "Mobile Home",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 159,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "boat_rv_van_etc",
        fieldAlias: "Boat, RV, van, etc.",
        fieldType: "Number",
        tableHeader: "Boat, RV, van, etc.",
        category: "Housing",
        indentLevel: 1,
        universeField: 0,
        rowID: 160,
        groupID: "<span class='myHiddenClass'>13</span>Housing",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "total_housing_units",
    },
    {
        fieldName: "total_occupied_hu",
        fieldAlias: "Occupied Housing Units",
        fieldType: "Number",
        tableHeader: "Occupied Housing Units",
        category: "Vehicles Available",
        indentLevel: 0,
        universeField: 1,
        rowID: 161,
        groupID: "<span class='myHiddenClass'>15</span>Vehicles Available",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "no_vehicle",
        fieldAlias: "No vehicle available",
        fieldType: "Number",
        tableHeader: "No vehicle available",
        category: "Vehicles Available",
        indentLevel: 1,
        universeField: 0,
        rowID: 162,
        groupID: "<span class='myHiddenClass'>15</span>Vehicles Available",
        chartCategory: "Vehicles",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_occupied_hu",
    },
    {
        fieldName: "one_vehicle",
        fieldAlias: "1 vehicle available",
        fieldType: "Number",
        tableHeader: "1 vehicle available",
        category: "Vehicles Available",
        indentLevel: 1,
        universeField: 0,
        rowID: 163,
        groupID: "<span class='myHiddenClass'>15</span>Vehicles Available",
        chartCategory: "Vehicles",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_occupied_hu",
    },
    {
        fieldName: "two_vehicles",
        fieldAlias: "2 vehicles available",
        fieldType: "Number",
        tableHeader: "2 vehicles available",
        category: "Vehicles Available",
        indentLevel: 1,
        universeField: 0,
        rowID: 164,
        groupID: "<span class='myHiddenClass'>15</span>Vehicles Available",
        chartCategory: "Vehicles",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_occupied_hu",
    },
    {
        fieldName: "three_plus_vehicles",
        fieldAlias: "3 or more vehicles available",
        fieldType: "Number",
        tableHeader: "3 or more vehicles available",
        category: "Vehicles Available",
        indentLevel: 1,
        universeField: 0,
        rowID: 165,
        groupID: "<span class='myHiddenClass'>15</span>Vehicles Available",
        chartCategory: "Vehicles",
        chartType: "pie",
        canSum: true,
        parentField: "",
        percentOfField: "total_occupied_hu",
    },
    {
        fieldName: "acres",
        fieldAlias: "Total Area in Acres",
        fieldType: "Number",
        tableHeader: "Total Area in Acres",
        category: "Area",
        indentLevel: 0,
        universeField: 0,
        rowID: 166,
        groupID: "<span class='myHiddenClass'>16</span>Area",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
    {
        fieldName: "sqmi",
        fieldAlias: "Total Area in Square Miles",
        fieldType: "Number",
        tableHeader: "Total Area in Square Miles",
        category: "Area",
        indentLevel: 0,
        universeField: 0,
        rowID: 167,
        groupID: "<span class='myHiddenClass'>16</span>Area",
        chartCategory: "",
        chartType: "",
        canSum: true,
        parentField: "",
        percentOfField: "",
    },
];
