(function() {

        "use strict";

        define(

            function() {
                var cbrConfig = new function() {
                    var self = this;
                    self.mapServices = {
                        blockGroups: appConfig.layerInfo[10].url
                    };

                    self.thematicMaps = [{
                            "NodeType": "cat",
                            "Name": "General",
                            "ShortName": "General",
                            "Description": "",
                            "items": [{
                                "NodeType": "map",
                                "LayerId": 0,
                                "Name": "Total Population",
                                "ShortName": "Total Population",
                                "Service": "blockGroups",
                                "DefaultColorRamp": "OrRd",
                                "DefaultColorScheme": "Sequential",
                                "Description": "",
                                "FieldName": "TOTAL_POP",
                                "Type": "number",
                                "Placeholder": 100000000
                            }, {
                                "NodeType": "map",
                                "LayerId": 0,
                                "Name": "Total Population Per Sq Mile",
                                "ShortName": "Total Population Per Sq Mile",
                                "Service": "blockGroups",
                                "DefaultColorRamp": "OrRd",
                                "DefaultColorScheme": "Sequential",
                                "Description": "",
                                "FieldName": "POP_PER_SQMI",
                                "Type": "number",
                                "Placeholder": 100000000
                            }]
                        }, {
                            "NodeType": "cat",
                            "Name": "Age",
                            "ShortName": "Age",
                            "Description": "Population by Age",
                            "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Under 5 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% Under 5 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_UNDER5",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 5 to 9 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 5 to 9 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "Source": "test",
                                    "FieldName": "PCT_AGE5TO9",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 10 to 14 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 10 to 14 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE10TO14",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 15 to 19 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 15 to 19 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE15TO19",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 20 to 24 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 20 to 24 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE20TO24",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 25 to 34 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 25 to 34 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE25TO34",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 35 to 44 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 35 to 44 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE35TO44",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 45 to 54 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 45 to 54 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE45TO54",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 55 to 59 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 55 to 59 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE55TO59",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 60 to 64 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 60 to 64 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE60TO64",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 65 to 74 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 65 to 74 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE65TO74",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 75 to 84 years",
                                    "Service": "blockGroups",
                                    "ShortName": "% 75 to 84 years",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE75TO84",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent 85 years and over",
                                    "Service": "blockGroups",
                                    "ShortName": "% 85 years and over",
                                    "DefaultColorRamp": "YlGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_AGE85PLUS",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "cat",
                                    "Name": "Select Age Groups",
                                    "ShortName": "Select Age Groups",
                                    "Description": "...",
                                    "items": [{
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent 18 years and over",
                                        "Service": "blockGroups",
                                        "ShortName": "% 18 years and over",
                                        "DefaultColorRamp": "YlGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_AGE18PLUS",
                                        "Type": "percent",
                                        "AsPercentages": true,
                                        "Placeholder": 100000000
                                    }, {
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent 21 years and over",
                                        "Service": "blockGroups",
                                        "ShortName": "% 21 years and over",
                                        "DefaultColorRamp": "YlGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_AGE_21PLUS",
                                        "Type": "percent",
                                        "AsPercentages": true,
                                        "Placeholder": 100000000
                                    }, {
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent 62 years and over",
                                        "Service": "blockGroups",
                                        "ShortName": "% 62 years and over",
                                        "DefaultColorRamp": "YlGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_AGE_62PLUS",
                                        "Type": "percent",
                                        "AsPercentages": true,
                                        "Placeholder": 100000000
                                    }, {
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent 65 years and over",
                                        "Service": "blockGroups",
                                        "ShortName": "% 65 years and over",
                                        "DefaultColorRamp": "YlGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_AGE_65PLUS",
                                        "Type": "percent",
                                        "AsPercentages": true,
                                        "Placeholder": 100000000
                                    }]
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Race and Ethnicity",
                                "ShortName": "Race and Ethnicity",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Hispanic",
                                    "Service": "blockGroups",
                                    "ShortName": "% Hispanic",
                                    "DefaultColorRamp": "GnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent White",
                                    "Service": "blockGroups",
                                    "ShortName": "% White Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_WHITE_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Black",
                                    "Service": "blockGroups",
                                    "ShortName": "% Black Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_BLACK_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Asian",
                                    "Service": "blockGroups",
                                    "ShortName": "% Asian Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_ASIAN_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Native American",
                                    "Service": "blockGroups",
                                    "ShortName": "% Native American Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_NATIVE_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Pacific Islander",
                                    "Service": "blockGroups",
                                    "ShortName": "% Pacific Islander Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_PACIFIC_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Two Or More Races",
                                    "Service": "blockGroups",
                                    "ShortName": "% Two or More Races  Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_TWO_OR_MORE_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Other Race",
                                    "Service": "blockGroups",
                                    "ShortName": "% Other Race Non-Hispanic",
                                    "DefaultColorRamp": "YlGnBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_OTHER_NON_HISPANIC",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Educational Attainment",
                                "ShortName": "Educational Attainment",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population with Education Less than 9th Grade",
                                    "Service": "blockGroups",
                                    "ShortName": "% Less than 9th Grade",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_LT9GRADE",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population with Education 9th to 12th Grade",
                                    "Service": "blockGroups",
                                    "ShortName": "% 9th to 12th Grade",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_NOHSDIPLOMA",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population High School Graduates",
                                    "Service": "blockGroups",
                                    "ShortName": "% High School / GED",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HSGRAD",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population with Some College",
                                    "Service": "blockGroups",
                                    "ShortName": "% Some College",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_SOMECOLLEGE",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population with Associates Degree",
                                    "Service": "blockGroups",
                                    "ShortName": "% Associates Degree",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_ASSOCIATES",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population with Bachelors Degree",
                                    "Service": "blockGroups",
                                    "ShortName": "% Bachelors Degree",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_BACHELORS",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent of Population with Graduate or Professional Degree",
                                    "Service": "blockGroups",
                                    "ShortName": "% Graduate or Professional Degree",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_GRADPROF",
                                    "AsPercentages": true,
                                    "Type": "percent"
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Ability to Speak English",
                                "ShortName": "Ability to Speak English",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Limited English Proficiency (LEP)",
                                    "Service": "blockGroups",
                                    "ShortName": "% Limited English Proficiency (LEP)",
                                    "DefaultColorRamp": "PuBu",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_LIMITED_ENG_PROF",
                                    "AsPercentages": true,
                                    "Type": "percent",
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Veteran Status",
                                "ShortName": "Veteran Status",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Civilian veterans",
                                    "Service": "blockGroups",
                                    "ShortName": "% Civilian veterans",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_VETERANS",
                                    "AsPercentages": true,
                                    "Type": "percent",
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Households",
                                "ShortName": "Households",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Households Per Sq Mile",
                                    "Service": "blockGroups",
                                    "ShortName": "Households Per Sq Mile",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "HH_PER_SQMI",
                                    "Type": "number",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Average Household Size",
                                    "Service": "blockGroups",
                                    "ShortName": "Average Household Size",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "AVG_HH_SIZE",
                                    "Type": "number",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Family Households",
                                    "Service": "blockGroups",
                                    "ShortName": "% Family Households",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_FAMILY_HOUSEHOLDS",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Nonfamily Households",
                                    "Service": "blockGroups",
                                    "ShortName": "% Nonfamily Households",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_NON_FAMILY_HOUSEHOLDS",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Household Income (in 2016 inflation-adjusted dollars)",
                                "ShortName": "Household Income (in 2016 inflation-adjusted dollars)",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Median Household Income (dollars)",
                                    "Service": "blockGroups",
                                    "ShortName": "Median Household Income (dollars)",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "MEDIAN_HOUSEHOLD_INCOME",
                                    "Type": "number",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Less than $10,000",
                                    "Service": "blockGroups",
                                    "ShortName": "% Less than $10,000",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_LESS_THAN_10K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $10,000 to $14,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $10,000 to $14,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_10K_TO_14K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $15,000 to $24,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $15,000 to $24,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_15K_TO_24K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $25,000 to $34,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $25,000 to $34,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_25K_TO_34K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $35,000 to 49,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $35,000 to 49,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_35K_TO_49K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $50,000 to $74,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $50,000 to $74,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_50K_TO_74K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $75,000 to $99,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $75,000 to $99,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_75K_TO_99K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $100,000 to $149,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $100,000 to $149,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_100K_TO_149K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $150,000 to $199,999",
                                    "Service": "blockGroups",
                                    "ShortName": "% $150,000 to $199,999",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_150K_TO_199K",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent $200,000 or more",
                                    "Service": "blockGroups",
                                    "ShortName": "% $200,000 or more",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_HH_200K_PLUS",
                                    "Type": "percent",
                                    "AsPercentages": true,
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Poverty Status in the Past 12 Months",
                                "ShortName": "Poverty Status in the Past 12 Months",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Families below poverty level",
                                    "Service": "blockGroups",
                                    "ShortName": "% Families Below poverty level",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_FAM_INCOME_BELOW_POVERTY",
                                    "AsPercentages": true,
                                    "Type": "percent",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "cat",
                                    "Name": "Persons",
                                    "ShortName": "Persons",
                                    "Description": "...",
                                    "items": [{
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent below poverty level",
                                        "Service": "blockGroups",
                                        "ShortName": "% Below poverty level",
                                        "DefaultColorRamp": "PuBuGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_INCOME_BELOW_POVERTY",
                                        "AsPercentages": true,
                                        "Type": "percent",
                                        "Placeholder": 100000000
                                    }, {
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent with income below 150% of poverty level",
                                        "Service": "blockGroups",
                                        "ShortName": "% Persons with income below 150% of poverty level",
                                        "DefaultColorRamp": "PuBuGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_INCOME_BELOW_150PCT_POVERTY",
                                        "Type": "percent",
                                        "AsPercentages": true,
                                        "Placeholder": 100000000
                                    }, {
                                        "NodeType": "map",
                                        "LayerId": 0,
                                        "Name": "Percent with income below 200% of poverty level",
                                        "Service": "blockGroups",
                                        "ShortName": "% Persons with income below 200% of poverty level",
                                        "DefaultColorRamp": "PuBuGn",
                                        "DefaultColorScheme": "Sequential",
                                        "Description": "",
                                        "FieldName": "PCT_INCOME_BELOW_200PCT_POVERTY",
                                        "Type": "percent",
                                        "AsPercentages": true,
                                        "Placeholder": 100000000
                                    }]
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Commuting to Work",
                                "ShortName": "Commuting to Work",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Car or Truck - drive alone",
                                    "Service": "blockGroups",
                                    "ShortName": "% Car or Truck - drive alone",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_DROVE_ALONE",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Car or Truck - carpool",
                                    "Service": "blockGroups",
                                    "ShortName": "% Car or Truck - carpool",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_CARPOOLED",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Public Transportation",
                                    "Service": "blockGroups",
                                    "ShortName": "% Public Transportation",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_PUBLIC_TRANSPORTATION",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Bicycle",
                                    "Service": "blockGroups",
                                    "ShortName": "% Bicycle",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_BICYCLE",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Walked",
                                    "Service": "blockGroups",
                                    "ShortName": "% Walked",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_WALKED",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Other means (taxicab, motorcycle, etc.)",
                                    "Service": "blockGroups",
                                    "ShortName": "% Other means (taxicab, motorcycle, etc.)",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_TAXI_MOTORCYCLE_OR_OTHER",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Work at home",
                                    "Service": "blockGroups",
                                    "ShortName": "% Work at home",
                                    "DefaultColorRamp": "PuBuGn",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": "",
                                    "FieldName": "PCT_WORKED_FROM_HOME",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Occupation",
                                "ShortName": "Occupation",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Management, business, science, and arts occupations",
                                    "Service": "blockGroups",
                                    "ShortName": "% Management, business, science, and arts occupations",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_MGBIZSCIART",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Service occupations",
                                    "Service": "blockGroups",
                                    "ShortName": "% Service occupations",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_SERVICEOCC",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Sales and office occupations",
                                    "Service": "blockGroups",
                                    "ShortName": "% Sales and office occupations",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_SALESOFFICEOCC",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Natural resources, construction, and maintenance occupations",
                                    "Service": "blockGroups",
                                    "ShortName": "% Natural resources, construction, and maintenance occupations",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_NATRESOURCES",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Production, transportation, and material moving occupations",
                                    "Service": "blockGroups",
                                    "ShortName": "% Production, transportation, and material moving occupations",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_PRODTRANSMATERIAL",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Housing",
                                "ShortName": "Housing",
                                "Description": "Contain housing units related variables",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Total Housing Units",
                                    "Service": "blockGroups",
                                    "ShortName": "Total Housing Units",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "TOTAL_HOUSING_UNITS",
                                    "Type": "number",
                                    // "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Median Value",
                                    "Service": "blockGroups",
                                    "ShortName": "Median Value",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "MEDIAN_VALUE",
                                    "Type": "number",
                                    // "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Median Rent",
                                    "Service": "blockGroups",
                                    "ShortName": "Median Rent",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "MEDIAN_GROSS_RENT",
                                    "Type": "number",
                                    // "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Occupied Housing Units",
                                    "Service": "blockGroups",
                                    "ShortName": "% Occupied Housing Units",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_OCCUPIED_HU",
                                    "AsPercentages": true,
                                    "Type": "percent",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Vacant Housing Units",
                                    "Service": "blockGroups",
                                    "ShortName": "% Vacant Housing Units",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_VACANT_HU",
                                    "AsPercentages": true,
                                    "Type": "percent",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "Percent Renter Occupied Housing Units",
                                    "Service": "blockGroups",
                                    "ShortName": "% Renter Occupied Housing Units",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_RENTER_OCCUPIED_HU",
                                    "AsPercentages": true,
                                    "Type": "percent",
                                    "Placeholder": 100000000
                                }]
                            },
                            {
                                "NodeType": "cat",
                                "Name": "Vehicles Available",
                                "ShortName": "Vehicles Available",
                                "Description": "...",
                                "items": [{
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% No Vehicle Available",
                                    "Service": "blockGroups",
                                    "ShortName": "% No Vehicle Available",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_NO_VEHICLE",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% One Vehicle Available",
                                    "Service": "blockGroups",
                                    "ShortName": "% One Vehicle Available",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_ONE_VEHICLE",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Two Vehicles Available",
                                    "Service": "blockGroups",
                                    "ShortName": "% Two Vehicles Available",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_TWO_VEHICLES",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }, {
                                    "NodeType": "map",
                                    "LayerId": 0,
                                    "Name": "% Three or More Vehicles Available",
                                    "Service": "blockGroups",
                                    "ShortName": "% Three or More Vehicles Available",
                                    "DefaultColorRamp": "OrRd",
                                    "DefaultColorScheme": "Sequential",
                                    "Description": null,
                                    "FieldName": "PCT_THREE_PLUS_VEHICLES",
                                    "Type": "percent",
                                    "AsPercentages": "TRUE",
                                    "Placeholder": 100000000
                                }]
                            }

                        ];
                    };
                    return cbrConfig;
                });
        }());
